window.WATCHDOG_INTEL = {
  "persona": {
    "nome": "Claudete",
    "papel": "Chief of Staff & Head of Marketing Analytics",
    "ultima_atualizacao": "2026-03-12T11:39:51.650703"
  },
  "ultima_atualizacao": "2026-03-17T23:53:01.339583",
  "arquitetura_memoria": {
    "modo": "camadas",
    "descricao": "Memoria viva enxuta + historico completo + resumos tematicos + indices.",
    "regras": {
      "memoria_viva": "Ultimos 24 aprendizados ativos e alertas abertos para uso frequente.",
      "historico": "Fonte permanente de know-how. Nunca deletar entradas do historico.",
      "resumos": "Primeira leitura para economizar token e acelerar contexto.",
      "indices": "Mapa rapido para abrir apenas o trecho historico necessario."
    }
  },
  "arquivos_relacionados": {
    "historico": "contexto/intel_historico.json",
    "resumos": "contexto/intel_resumos.json",
    "indices": "contexto/intel_indices.json"
  },
  "memoria_viva": {
    "insights_ativos_total_historico": 127,
    "insights_expostos_neste_arquivo": 24,
    "alertas_abertos_total_historico": 46,
    "alertas_expostos_neste_arquivo": 46,
    "temas_prioritarios": [
      "sdr",
      "base",
      "rr_sdr",
      "geral",
      "renovacao",
      "copy",
      "concorrencia",
      "outbound"
    ]
  },
  "resumos_tematicos": [
    {
      "tema": "sdr",
      "titulo": "SDR",
      "resumo_executivo": "Aprendizados-chave: Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na sema... | HT PÚB Renovação apresenta zero absoluto na semana (0 realizadas, 0 fechadas, RR/SDR 0/2,29) mesmo com LT Pública e HT Pública acumulando potencial de receita relevante (R$96.81... Riscos abertos: HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positiv... | Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de aluno...",
      "aprendizados_ids": [
        "insight128",
        "insight130",
        "insight115",
        "insight119",
        "insight104",
        "insight110",
        "insight081",
        "insight082",
        "insight083",
        "insight084",
        "insight085",
        "insight086",
        "insight089",
        "insight090",
        "insight091",
        "insight095",
        "insight096",
        "insight097",
        "insight078",
        "insight079",
        "insight080",
        "insight073",
        "insight071",
        "insight068",
        "insight069",
        "insight051",
        "insight053",
        "insight054",
        "insight061",
        "insight025",
        "insight027",
        "insight029",
        "insight031",
        "insight032",
        "insight033",
        "insight034",
        "insight035",
        "insight041",
        "insight002",
        "insight010",
        "insight012",
        "insight016",
        "insight018",
        "insight020",
        "insight021",
        "insight017",
        "insight121"
      ],
      "alertas_ids": [
        "alerta057",
        "alerta058",
        "alerta061",
        "alerta045",
        "alerta046",
        "alerta039",
        "alerta040",
        "alerta042",
        "alerta036",
        "alerta037",
        "alerta032",
        "alerta030",
        "alerta025",
        "alerta026",
        "alerta024",
        "alerta020",
        "alerta012",
        "alerta014",
        "alerta001",
        "alerta004",
        "alerta005",
        "alerta006",
        "alerta009",
        "alerta051",
        "alerta052"
      ],
      "aprendizados_chave": [
        "Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na sema...",
        "HT PÚB Renovação apresenta zero absoluto na semana (0 realizadas, 0 fechadas, RR/SDR 0/2,29) mesmo com LT Pública e HT Pública acumulando potencial de receita relevante (R$96.81...",
        "Retração apresenta desacoplamento entre meta de alunos (verde, 106% YTD) e RR/SDR (62% da meta). Isso indica que quando as reuniões acontecem, os alunos chegam em volume acima d..."
      ],
      "riscos_abertos": [
        "HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positiv...",
        "Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de aluno..."
      ],
      "contagem_aprendizados": 48,
      "contagem_alertas_abertos": 25,
      "ultima_atualizacao": "2026-03-17"
    },
    {
      "tema": "base",
      "titulo": "Base",
      "resumo_executivo": "Aprendizados-chave: LT PART dobrou o número de convertidas entre a última daily registrada (7-8) e hoje (16/30 = 53%), mas a receita avançou proporcionalmente menos: de ~R$24k para R$42k (43% da me... | LT PART exibe descolamento crescente entre % de convertidas e % de receita: em 17/03 convertidas chegam a 53% da meta (16/30) enquanto receita está em 42% (R$42.244/R$98.649). O... Riscos abertos: LT PART hoje: 16/30 convertidas (53%) e R$42.244/R$98.649 em receita (42%). O alerta045 registrava 7 convertidas e R$24k. Houve avanço real (dobrou convertidas), mas a receita n... | Com 16/30 convertidas (53%) e R$42.244/R$98.649 de receita (42%), fechar as 14 convertidas restantes ao ticket médio atual de R$2.640 geraria apenas R$79.204 — abaixo da meta de...",
      "aprendizados_ids": [
        "insight127",
        "insight129",
        "insight112",
        "insight114",
        "insight115",
        "insight118",
        "insight102",
        "insight103",
        "insight106",
        "insight107",
        "insight110",
        "insight096",
        "insight097",
        "insight099",
        "insight100",
        "insight077",
        "insight078",
        "insight080",
        "insight073",
        "insight072",
        "insight070",
        "insight068",
        "insight065",
        "insight067",
        "insight047",
        "insight049",
        "insight044",
        "insight051",
        "insight058",
        "insight030",
        "insight032",
        "insight040",
        "insight041",
        "insight003",
        "insight004",
        "insight005",
        "insight007",
        "insight011",
        "insight018",
        "insight021",
        "insight122",
        "insight124"
      ],
      "alertas_ids": [
        "alerta056",
        "alerta059",
        "alerta061",
        "alerta045",
        "alerta046",
        "alerta037",
        "alerta032",
        "alerta033",
        "alerta026",
        "alerta020",
        "alerta021",
        "alerta017",
        "alerta005",
        "alerta007",
        "alerta011",
        "alerta053"
      ],
      "aprendizados_chave": [
        "LT PART dobrou o número de convertidas entre a última daily registrada (7-8) e hoje (16/30 = 53%), mas a receita avançou proporcionalmente menos: de ~R$24k para R$42k (43% da me...",
        "LT PART exibe descolamento crescente entre % de convertidas e % de receita: em 17/03 convertidas chegam a 53% da meta (16/30) enquanto receita está em 42% (R$42.244/R$98.649). O...",
        "LT PART acumula evidência de que o gargalo não é ausência de disparo nem de base cadastrada — é conversão pós-disparo. Com 272 alunos cadastrados e R$731 de custo de disparo já..."
      ],
      "riscos_abertos": [
        "LT PART hoje: 16/30 convertidas (53%) e R$42.244/R$98.649 em receita (42%). O alerta045 registrava 7 convertidas e R$24k. Houve avanço real (dobrou convertidas), mas a receita n...",
        "Com 16/30 convertidas (53%) e R$42.244/R$98.649 de receita (42%), fechar as 14 convertidas restantes ao ticket médio atual de R$2.640 geraria apenas R$79.204 — abaixo da meta de..."
      ],
      "contagem_aprendizados": 42,
      "contagem_alertas_abertos": 16,
      "ultima_atualizacao": "2026-03-17"
    },
    {
      "tema": "rr_sdr",
      "titulo": "RR/SDR",
      "resumo_executivo": "Aprendizados-chave: Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na sema... | HT PÚB Renovação apresenta zero absoluto na semana (0 realizadas, 0 fechadas, RR/SDR 0/2,29) mesmo com LT Pública e HT Pública acumulando potencial de receita relevante (R$96.81... Riscos abertos: HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positiv... | Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de aluno...",
      "aprendizados_ids": [
        "insight128",
        "insight130",
        "insight119",
        "insight104",
        "insight095",
        "insight097",
        "insight054",
        "insight061",
        "insight031",
        "insight012",
        "insight021",
        "insight121"
      ],
      "alertas_ids": [
        "alerta057",
        "alerta058",
        "alerta061",
        "alerta040",
        "alerta042",
        "alerta032",
        "alerta030",
        "alerta026",
        "alerta024",
        "alerta004",
        "alerta005",
        "alerta051",
        "alerta052"
      ],
      "aprendizados_chave": [
        "Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na sema...",
        "HT PÚB Renovação apresenta zero absoluto na semana (0 realizadas, 0 fechadas, RR/SDR 0/2,29) mesmo com LT Pública e HT Pública acumulando potencial de receita relevante (R$96.81...",
        "Retração apresenta desacoplamento entre meta de alunos (verde, 106% YTD) e RR/SDR (62% da meta). Isso indica que quando as reuniões acontecem, os alunos chegam em volume acima d..."
      ],
      "riscos_abertos": [
        "HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positiv...",
        "Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de aluno..."
      ],
      "contagem_aprendizados": 12,
      "contagem_alertas_abertos": 13,
      "ultima_atualizacao": "2026-03-17"
    },
    {
      "tema": "geral",
      "titulo": "Geral",
      "resumo_executivo": "Riscos abertos: HT Pública registra 427 alunos cadastrados e potencial de R$61.488,30 em ações de MKT, mas o comercial entregou 0 realizadas e 0 fechadas na semana. A t187 (Pimentel mapear caus... | Pimentel sinalizou problema de contabilização de escolas convertidas ao final da daily — sem DRI ou prazo definidos. Distorce todas as métricas de meta.",
      "aprendizados_ids": [
        "insight116",
        "insight123"
      ],
      "alertas_ids": [
        "alerta060",
        "alerta047",
        "alerta038",
        "alerta034",
        "alerta029",
        "alerta023",
        "alerta015",
        "alerta016",
        "alerta050",
        "alerta054",
        "alerta055"
      ],
      "aprendizados_chave": [],
      "riscos_abertos": [
        "HT Pública registra 427 alunos cadastrados e potencial de R$61.488,30 em ações de MKT, mas o comercial entregou 0 realizadas e 0 fechadas na semana. A t187 (Pimentel mapear caus...",
        "Pimentel sinalizou problema de contabilização de escolas convertidas ao final da daily — sem DRI ou prazo definidos. Distorce todas as métricas de meta."
      ],
      "contagem_aprendizados": 2,
      "contagem_alertas_abertos": 11,
      "ultima_atualizacao": "2026-03-17"
    },
    {
      "tema": "renovacao",
      "titulo": "Renovacao",
      "resumo_executivo": "Aprendizados-chave: HT PÚB Renovação exibe colapso semanal recorrente de realizadas apesar de meta YTD de receita em verde: quando o volume de reuniões cai a zero em uma semana, a altíssima taxa de... | LT PART dobrou o número de convertidas entre a última daily registrada (7-8) e hoje (16/30 = 53%), mas a receita avançou proporcionalmente menos: de ~R$24k para R$42k (43% da me... Riscos abertos: HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positiv... | A semana de 03-06/mar encerrou com HT PART Renovação em 79% do RR/SDR semanal. Na daily 06/mar, as 22 RRs necessárias no último dia eram matematicamente impossíveis. O deficit d...",
      "aprendizados_ids": [
        "insight126",
        "insight127",
        "insight129",
        "insight130",
        "insight111",
        "insight114",
        "insight118",
        "insight120",
        "insight104",
        "insight109",
        "insight092",
        "insight093",
        "insight080",
        "insight073",
        "insight051",
        "insight026",
        "insight028",
        "insight031",
        "insight036",
        "insight038",
        "insight039",
        "insight002",
        "insight003",
        "insight004",
        "insight006",
        "insight007",
        "insight009",
        "insight018",
        "insight017",
        "insight023",
        "insight125"
      ],
      "alertas_ids": [
        "alerta057",
        "alerta032",
        "alerta030",
        "alerta026",
        "alerta024",
        "alerta005",
        "alerta009"
      ],
      "aprendizados_chave": [
        "HT PÚB Renovação exibe colapso semanal recorrente de realizadas apesar de meta YTD de receita em verde: quando o volume de reuniões cai a zero em uma semana, a altíssima taxa de...",
        "LT PART dobrou o número de convertidas entre a última daily registrada (7-8) e hoje (16/30 = 53%), mas a receita avançou proporcionalmente menos: de ~R$24k para R$42k (43% da me...",
        "LT PART exibe descolamento crescente entre % de convertidas e % de receita: em 17/03 convertidas chegam a 53% da meta (16/30) enquanto receita está em 42% (R$42.244/R$98.649). O..."
      ],
      "riscos_abertos": [
        "HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positiv...",
        "A semana de 03-06/mar encerrou com HT PART Renovação em 79% do RR/SDR semanal. Na daily 06/mar, as 22 RRs necessárias no último dia eram matematicamente impossíveis. O deficit d..."
      ],
      "contagem_aprendizados": 31,
      "contagem_alertas_abertos": 7,
      "ultima_atualizacao": "2026-03-17"
    },
    {
      "tema": "copy",
      "titulo": "Copy",
      "resumo_executivo": "Aprendizados-chave: No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc... | Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-... Riscos abertos: Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao... | Concorrencia abriu marco com 45% de fechadas/realizadas vs 58% em fevereiro - queda de 13pp sem causa documentada. Com 1 SDR a menos e bolsao herdado de fev, risco de degradacao...",
      "aprendizados_ids": [
        "insight115",
        "insight117",
        "insight103",
        "insight106",
        "insight110",
        "insight087",
        "insight093",
        "insight094",
        "insight099",
        "insight100",
        "insight075",
        "insight080",
        "insight070",
        "insight067",
        "insight061",
        "insight050",
        "insight042",
        "insight043",
        "insight052",
        "insight053",
        "insight057",
        "insight026",
        "insight003",
        "insight009",
        "insight018",
        "insight024"
      ],
      "alertas_ids": [
        "alerta040",
        "alerta025",
        "alerta018",
        "alerta012",
        "alerta013",
        "alerta007",
        "alerta011"
      ],
      "aprendizados_chave": [
        "No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc...",
        "Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-...",
        "Copy de benefícios para Anos Anteriores performa melhor em escolas sem SDR atribuído — cold outreach WA é mais efetivo sem interferência de relacionamento prévio com SDR."
      ],
      "riscos_abertos": [
        "Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao...",
        "Concorrencia abriu marco com 45% de fechadas/realizadas vs 58% em fevereiro - queda de 13pp sem causa documentada. Com 1 SDR a menos e bolsao herdado de fev, risco de degradacao..."
      ],
      "contagem_aprendizados": 26,
      "contagem_alertas_abertos": 7,
      "ultima_atualizacao": "2026-03-13"
    },
    {
      "tema": "concorrencia",
      "titulo": "Concorrencia",
      "resumo_executivo": "Aprendizados-chave: Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na sema... | Campanhas de ativação de lista têm KPI primário diferente de levantada — alunos cadastrados e convertidas são o indicador correto, não CPL de levantada Riscos abertos: Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de aluno... | Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes.",
      "aprendizados_ids": [
        "insight128",
        "insight086",
        "insight091",
        "insight093",
        "insight094",
        "insight095",
        "insight077",
        "insight078",
        "insight080",
        "insight071",
        "insight072",
        "insight070",
        "insight068",
        "insight067",
        "insight053",
        "insight061",
        "insight050",
        "insight042",
        "insight044",
        "insight052",
        "insight025",
        "insight027",
        "insight028",
        "insight029",
        "insight031",
        "insight032",
        "insight035",
        "insight036",
        "insight037",
        "insight002",
        "insight006",
        "insight011",
        "insight021",
        "insight017"
      ],
      "alertas_ids": [
        "alerta058",
        "alerta042",
        "alerta037",
        "alerta025",
        "alerta021"
      ],
      "aprendizados_chave": [
        "Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na sema...",
        "Campanhas de ativação de lista têm KPI primário diferente de levantada — alunos cadastrados e convertidas são o indicador correto, não CPL de levantada",
        "O Cerco Mágico usa dois objetos físicos com funções distintas: (1) Revista Estante Mágica = mala direta tabloide para 4.716 escolas (AA+Ret+Conc), cria reconhecimento de marca;..."
      ],
      "riscos_abertos": [
        "Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de aluno...",
        "Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes."
      ],
      "contagem_aprendizados": 34,
      "contagem_alertas_abertos": 5,
      "ultima_atualizacao": "2026-03-17"
    },
    {
      "tema": "outbound",
      "titulo": "Outbound",
      "resumo_executivo": "Aprendizados-chave: Priorização de escolas High Value no Outbound pode reduzir volume de levantadas porque histórico mostra que escolas de médio e micro porte são as que mais convertem nesse canal.... | Base WA da Estante Mágica possui 19 campos de telefone, mas apenas 2 são utilizados nos disparos — potencial de expansão de raio em ~9,5x sem custo adicional de aquisição. Riscos abertos: Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análi... | Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao...",
      "aprendizados_ids": [
        "insight115",
        "insight101",
        "insight107",
        "insight108",
        "insight098",
        "insight099",
        "insight077",
        "insight068",
        "insight067",
        "insight054",
        "insight043",
        "insight044",
        "insight025",
        "insight027",
        "insight032",
        "insight001",
        "insight005",
        "insight008",
        "insight011",
        "insight024",
        "insight124"
      ],
      "alertas_ids": [
        "alerta046",
        "alerta040",
        "alerta018",
        "alerta011",
        "alerta053"
      ],
      "aprendizados_chave": [
        "Priorização de escolas High Value no Outbound pode reduzir volume de levantadas porque histórico mostra que escolas de médio e micro porte são as que mais convertem nesse canal....",
        "Base WA da Estante Mágica possui 19 campos de telefone, mas apenas 2 são utilizados nos disparos — potencial de expansão de raio em ~9,5x sem custo adicional de aquisição.",
        "Segmentação exclusiva em High Value pode estar deprimindo taxa de levantadas no Outbound: queda de 5 para 3,75 levantadas/disparo vs ano anterior (-25%), pois escolas médio e mi..."
      ],
      "riscos_abertos": [
        "Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análi...",
        "Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao..."
      ],
      "contagem_aprendizados": 21,
      "contagem_alertas_abertos": 5,
      "ultima_atualizacao": "2026-03-13"
    }
  ],
  "aprendizados": [
    {
      "id": "insight126",
      "data": "2026-03-17",
      "fonte": "Nath 17.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "insight": "HT PÚB Renovação exibe colapso semanal recorrente de realizadas apesar de meta YTD de receita em verde: quando o volume de reuniões cai a zero em uma semana, a altíssima taxa de fechamento da frente (históricamente >80%) não consegue compensar — o produto da frente depende exclusivamente de topo de funil ativo. Ausência de abastecimento por uma semana zera a frente completamente, independentemente da qualidade de conversão.",
      "evidencia": "HT PÚB semanal: Realizadas 0/11 (0%), Tx fechadas/realizadas 0%/80% (0% da meta), RR/SDR 0/2,29 (0%). Meta mensal YTD de receita em 355% — ou seja, a frente já supera a meta acumulada de receita mas zerou operacionalmente nesta semana.",
      "aplicavel_a": [
        "HT PUB",
        "Renovação",
        "abastecimento de topo de funil"
      ],
      "acao_sugerida": "Em HT PÚB, monitorar Realizadas semanais como leading indicator prioritário — qualquer semana com Realizadas < 5 deve disparar alerta automático antes da daily de quarta, pois uma semana zerada não é recuperável pelo fechamento, dado que a taxa de conversão já opera no teto.",
      "status": "ativo"
    },
    {
      "id": "insight127",
      "data": "2026-03-17",
      "fonte": "Nath 17.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "campanha",
      "insight": "LT PART dobrou o número de convertidas entre a última daily registrada (7-8) e hoje (16/30 = 53%), mas a receita avançou proporcionalmente menos: de ~R$24k para R$42k (43% da meta de receita vs 53% de convertidas). Isso indica que as convertidas incrementais desta semana têm ticket médio inferior às anteriores — possível efeito de composição de base (escolas menores ou com menos alunos sendo priorizadas na régua de ativação pós-disparo).",
      "evidencia": "LT PART: Meta convertidas 16/30 (53%), Meta receita R$42.244/R$98.649 (42%). Razão receita/convertidas atual: R$2.640/convertida vs meta implícita R$3.288/convertida (R$98.649/30).",
      "aplicavel_a": [
        "LT PART",
        "Renovação",
        "ticket médio",
        "segmentação de base"
      ],
      "acao_sugerida": "Ao analisar LT PART, sempre comparar % de convertidas vs % de receita — divergência acima de 8pp sugere drift de ticket médio e deve levar a revisão do critério de priorização da régua de ativação (escolas maiores primeiro).",
      "status": "ativo"
    },
    {
      "id": "insight128",
      "data": "2026-03-17",
      "fonte": "Nath 17.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "insight": "Frentes de Novas (AA, Concorrência, Retração, Novas) exibem um padrão sistemático de 0% na meta de alunos semanal — todas as quatro frentes registram 0 alunos realizados na semana atual. Isso não é falha individual: é sinal estrutural de que a semana corrente ainda não processou fechamentos (possível lag de contabilização ou semana iniciante). O padrão deve ser diferenciado de colapso real antes de gerar ação.",
      "evidencia": "AA semana: 0/1.318 (0%). Concorrência semana: 0/897 (0%). Novas semana: 0/525 (0%). As três frentes têm Realizadas e RR/SDR saudáveis na semana (AA 240%, Concorrência 189%, Novas 115%), o que confirma que o zero de alunos é lag de contabilização, não zero de atividade.",
      "aplicavel_a": [
        "AA",
        "Concorrência",
        "Novas",
        "contabilização semanal"
      ],
      "acao_sugerida": "Nas dailies de terça-feira, tratar meta de alunos semanal = 0 com cautela — cruzar sempre com Realizadas e RR/SDR da mesma semana antes de gerar alerta. Zero de alunos com Realizadas saudável = lag; zero de alunos com Realizadas também zerada = alerta real.",
      "status": "ativo"
    },
    {
      "id": "insight129",
      "data": "2026-03-17",
      "fonte": "Nath 17.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "insight": "LT PART exibe descolamento crescente entre % de convertidas e % de receita: em 17/03 convertidas chegam a 53% da meta (16/30) enquanto receita está em 42% (R$42.244/R$98.649). O ticket médio implícito por convertida caiu de R$3.428 (fase inicial, ~7 convertidas) para R$2.640 (hoje, 16 convertidas). A tendência sugere que as convertidas incrementais são sistematicamente de escolas menores — a régua de ativação pós-disparo pode estar priorizando volume sobre valor, ou as escolas maiores da base simplesmente não estão respondendo ao disparo atual.",
      "evidencia": "16/30 convertidas (53%) vs R$42.244/R$98.649 em receita (42%); base cadastrada de 451 alunos com custo de disparo R$731,16. Ticket médio implícito: R$2.640 por convertida em 17/03 vs R$3.428 calculado com 7 convertidas na daily anterior.",
      "aplicavel_a": [
        "LT PART",
        "Renovação",
        "estratégia de ativação de base"
      ],
      "acao_sugerida": "Sempre monitorar o par convertidas+receita em LT PART como duplo KPI: quando a % de convertidas supera a % de receita em mais de 8pp, é sinal de degradação de ticket médio e a base deve ser reordenada por tamanho de escola antes do próximo ciclo de disparo.",
      "status": "ativo"
    },
    {
      "id": "insight130",
      "data": "2026-03-17",
      "fonte": "Nath 17.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "insight": "HT PÚB Renovação apresenta zero absoluto na semana (0 realizadas, 0 fechadas, RR/SDR 0/2,29) mesmo com LT Pública e HT Pública acumulando potencial de receita relevante (R$96.812 e R$61.488 respectivamente em LT/HT Pública nas ações de MKT). Isso indica que o pipeline de ativação de LT e HT Pública existe no nível de marketing (alunos cadastrados, potencial mapeado), mas não está se convertendo em reuniões realizadas pelo comercial. O gargalo não é geração de interesse — é passagem de bastão entre MKT e comercial para estas frentes.",
      "evidencia": "HT PÚB: 0 realizadas/11 meta semanal, Tx fechadas 0%/80%; LT Pública: 35 convertidas, 1.827 alunos cadastrados, potencial R$96.812; HT Pública: 5 convertidas, 427 alunos cadastrados, potencial R$61.488.",
      "aplicavel_a": [
        "HT PÚB",
        "LT Pública",
        "Renovação",
        "handoff MKT-Comercial"
      ],
      "acao_sugerida": "Sempre que HT PÚB ou LT Pública registrarem zero de realizadas em uma semana, verificar se existe fila de leads disponíveis para o comercial antes de diagnosticar problema de geração de demanda — o potencial de receita nas ações de MKT pode estar represado por falta de acionamento comercial.",
      "status": "ativo"
    },
    {
      "id": "insight111",
      "titulo": "Caneca e Sem trabalho sao as melhores ofertas para Renovacao HT como levantada — CPL < R$12 confirmado em Feb e Mar/2026",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Caneca Feb/23: CPL R$6.60 (54 lev). Caneca Feb/25: CPL R$11.38 (29 lev). Sem trabalho Publica Mar/09: CPL R$8.94 (9 lev). Sem trabalho Particular Mar/10: CPL R$10.22 (41 lev). Playlist Renovacao Mar/03: objetivo era conversao (cadastro de alunos), nao levantada — gerou 3+3+2 convertidas, avaliacao de eficacia como conversao pendente. Nao comparar Playlist com Caneca/Sem trabalho para objetivo de levantada.",
      "acao_sugerida": "Priorizar Caneca e Sem trabalho em disparos de Renovacao HT com objetivo de levantada. Playlist tem objetivo distinto (conversao de alunos) e nao deve ser comparado diretamente. Avaliar CPL de Playlist como custo por cadastro de alunos, nao por levantada.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026",
      "ultima_atualizacao": "2026-03-13T08:53:35.944357"
    },
    {
      "id": "insight112",
      "titulo": "Anos Anteriores tem CPL estruturalmente baixo (R$3-6) independente da oferta — segmento mais eficiente do portfolio",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Jan/12 Presente exclusivo: CPL ~R$3.02 (68 lev/623 base). Jan/27 Visibilidade: CPL ~R$5.76 (30 lev). Feb/03 Playlist: CPL ~R$4.60 (94 lev/1205 base). Feb/25 Caneca: CPL ~R$4.53 (114 lev/1413 base). Mar/11 Beneficios especiais: CPL ~R$22.74 (18 lev, base menor).",
      "acao_sugerida": "Priorizar AA em semanas de orcamento restrito. Qualquer oferta funciona neste segmento. Escalar base quando disponivel.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026"
    },
    {
      "id": "insight113",
      "titulo": "Retracao A/B Mar/2026: Presente exclusivo supera Sem trabalho (2.65% vs 1.47%, CPL R$20 vs R$37)",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Teste A/B 11/03/2026 — Presente exclusivo: 7 lev de 549 base (2.65%), CPL R$20.37. Sem trabalho: 4 lev de 520 base (1.47%), CPL R$36.86. Volume absoluto baixo — Retracao tem engajamento estruturalmente menor que outros baldinhos.",
      "acao_sugerida": "Usar Presente exclusivo como oferta padrao para Retracao. Nao repetir Sem trabalho neste segmento sem nova hipotese clara. Volume permanece baixo — Retracao precisa de abordagem complementar alem de disparo WA.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026"
    },
    {
      "id": "insight114",
      "titulo": "Renovacao Publica HT tem CPL historico abaixo de R$9 — segmento estruturalmente eficiente mesmo com base pequena",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Feb/09 (>5k Publica): CPL R$7.02, 55 lev de 443 base (12.4%). Mar/09 (HT Publica Sem trabalho): CPL R$8.94, 9 lev de 210 base (4.3%). Consistente em dois meses com ofertas diferentes.",
      "acao_sugerida": "Manter Renovacao Publica HT na programacao mensal. Priorizar em janelas de orcamento reduzido. Base pequena mas qualidade alta.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026"
    },
    {
      "id": "insight115",
      "titulo": "Outbound SDR via WA tem CPL nao-sustentavel em bases grandes (>500) — padrao confirmado Jan, Feb e Mar/2026",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Jan/29 (1186 base): 9 lev, CPL R$34.92. Feb/23 (3118 base, Playlist): 2 lev, CPL R$361.26. Mar/12 (2625 base HV — High Value — ja segmentada, menor parcela): 5 lev, CPL R$121.72. Confirmado: base Mar/12 era exclusivamente HV, ja qualificada. O problema nao e segmentacao de qualidade — e que WA Outbound nao funciona nem para HV em volume. Padrao: qualquer base Outbound > 500 produziu CPL acima de R$30.",
      "acao_sugerida": "Suspender disparos Outbound SDR em bases > 500. Mesmo com base HV qualificada, resultado e insatisfatorio. Testar micro-lotes (<200 contatos HV) com copy especifico para perfil HV antes de escalar. Investigar se o canal WA e adequado para HV ou se o perfil HV responde melhor a outro canal (email, SDR direto). Ver alerta046 e alerta011.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026",
      "ultima_atualizacao": "2026-03-13T08:53:35.944357"
    },
    {
      "id": "insight116",
      "titulo": "Via herois na planilha de controles = total mensal de levantadas de todos os canais (WA disparos + CS form + Instagram + email + mala direta)",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Marco/2026 (ate 12/03): 103 total incluindo WA disparos (89 calculados) + canais organicos (~14). Fevereiro/2026: 257 total dividido em Instagram (31), email (18) e herois (208 = WA disparos + CS form + mala direta combinados). Corrigido em 13/03 via feedback da Vit: '103 e o total das levantadas do mes, incluindo disparos. Ta incluso os disparos que estamos fazendo, levantadas que vem por herois, mala direta, email, instagram, etc.' Insight anterior (errado) dizia que herois = canal gratuito separado dominando 81% das levantadas. Incorreto.",
      "acao_sugerida": "Ao ler a planilha de controles da Vit, tratar o campo 'Via herois' como totalizador mensal — nao como canal isolado. Os WA disparos sao rastreados individualmente nas linhas acima; o totalizador agrega tudo. Para calcular levantadas organicas (nao-disparo), subtrair o total dos disparos WA do total mensal.",
      "contexto": "Resposta da Vit ao debriefing da planilha de disparos Mar/2026",
      "fonte": "feedback_vit_13_03_2026",
      "ultima_atualizacao": "2026-03-13T09:00:18.964513"
    },
    {
      "id": "insight117",
      "titulo": "MEL (Mes da Estrela Literaria) = campanha 2024 que funcionou mas foi descontinuada por limitacao operacional, nao por resultado",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Confirmado por Pedro em 13/03/2026. MEL = Mes da Estrela Literaria. Campanha com serie de acoes e beneficios para a escola ao longo de um mes. Gerou levantadas em 2024. Descontinuada porque a execucao exigia capacidade interna que o time nao tinha. Hipotese (Lili, 04/mar/26): queda de levantadas 2024->2025 correlacionada com fim do MEL. O argumento central era a escola como protagonista literaria com beneficios multiplos e destaque. Insight087 corrigido com essa definicao.",
      "acao_sugerida": "Extrair o ARGUMENTO do MEL (escola protagonista, reconhecimento publico, beneficios multiplos, mes dedicado) e adaptar para o copy dos e-mails do Cerco Magico 2026 — especialmente AA e Retracao — sem precisar da estrutura operacional completa. O argumento 'sua escola vira uma escola de autores por um mes inteiro' pode funcionar como gancho mesmo que o programa MEL nao exista mais com esse nome. Karina e Lili validar qual elemento do MEL pode ser reposicionado no copy atual.",
      "contexto": "Feedback Pedro em sessao Claudete 13/03/2026",
      "fonte": "feedback_pedro_13_03_2026"
    },
    {
      "id": "insight118",
      "data": "2026-03-13",
      "fonte": "Nath 13.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "gatilho": "LT PART",
      "insight": "LT PART acumula evidência de que o gargalo não é ausência de disparo nem de base cadastrada — é conversão pós-disparo. Com 272 alunos cadastrados e R$731 de custo de disparo já executados, a frente chegou a 8 convertidas em 30 (23% de meta de convertidas) e R$24k de R$98k em receita. O problema não é operacional de execução de campanha; é estrutural de proposta de valor ou timing de abordagem para este segmento.",
      "evidencia": "Meta Marketing LT PART: R$24.000/R$98.649 (24%). Convertidas: 8/30 (23%). Alunos cadastrados: 272. Custo disparo: R$731,16. Dados confirmados em documento de 13/03 após alerta045 que registrou o mesmo patamar na semana anterior — sem recuperação.",
      "confianca": "alta",
      "aplicavel_a": [
        "LT PART",
        "renovação",
        "campanha de baixo toque"
      ],
      "acao_sugerida": "Antes de escalar volume de disparo LT PART, auditar proposta de valor e timing: o que está sendo oferecido, em que momento do ciclo e com qual argumento. Volume sem ajuste de mensagem apenas aumenta custo sem mover conversão.",
      "status": "ativo"
    },
    {
      "id": "insight119",
      "data": "2026-03-13",
      "fonte": "Nath 13.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "gatilho": "Retração RR/SDR",
      "insight": "Retração apresenta desacoplamento entre meta de alunos (verde, 106% YTD) e RR/SDR (62% da meta). Isso indica que quando as reuniões acontecem, os alunos chegam em volume acima do esperado — mas o volume de reuniões em si está comprimido. O gargalo de Retração não é conversão por reunião, é abastecimento de topo de funil (reuniões realizadas).",
      "evidencia": "Retração mês: Meta alunos 1.888/4.355 (106% YTD verde). RR/SDR: 0,40/0,64 (62% da meta). Realizadas: 17/56 (74% YTD). A taxa de fechadas/realizadas de 47%/62% (76% meta) indica que quando a reunião ocorre, o fechamento é razoável — o problema é chegar a 56 reuniões.",
      "confianca": "alta",
      "aplicavel_a": [
        "Retração",
        "abastecimento de funil",
        "SDR"
      ],
      "acao_sugerida": "Em Retração, priorizar ações que aumentem volume de reuniões realizadas (abastecimento SDR, cadência de follow-up) antes de investir em melhoria de taxa de fechamento — a conversão por reunião já está razoável.",
      "status": "ativo"
    },
    {
      "id": "insight120",
      "data": "2026-03-13",
      "fonte": "Nath 13.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "gatilho": "LT Pública",
      "insight": "LT Pública mostra potencial de receita (R$72.198 potencial, 25 convertidas, 1.482 alunos cadastrados) desproporcional ao custo de disparo (R$283,50). O custo por aluno cadastrado de LT Pública é significativamente inferior ao de LT PART (R$283/1.482 = R$0,19/aluno vs R$731/272 = R$2,69/aluno). Quando HT PÚB e LT Pública operam em conjunto no segmento público, a eficiência de custo de campanha é uma ordem de grandeza maior que no segmento particular.",
      "evidencia": "LT Pública: Potencial R$72.198,75. Convertidas: 25. Alunos cadastrados: 1.482. Custo disparo: R$283,50. HT Pública: Potencial R$54.608,51. Convertidas: 5. Alunos cadastrados: 427. Custo disparo: R$262,44.",
      "confianca": "media",
      "aplicavel_a": [
        "LT Pública",
        "HT Pública",
        "alocação de budget de campanha"
      ],
      "acao_sugerida": "Ao planejar alocação de budget de campanha de renovação, priorizar segmento público por custo por aluno cadastrado significativamente inferior. LT Pública especificamente deve receber escala antes de LT PART quando há restrição de budget.",
      "status": "ativo"
    },
    {
      "id": "insight101",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "gatilho": "queda levantadas Outbound 5 para 3,75",
      "insight": "Priorização de escolas High Value no Outbound pode reduzir volume de levantadas porque histórico mostra que escolas de médio e micro porte são as que mais convertem nesse canal. Alta segmentação por valor unitário inverte a lógica de volume que sustenta o funil Outbound.",
      "evidencia": "Vitória reportou queda de média de levantadas de 5 para 3,75 por disparo vs ano anterior. Lili e Vit levantaram hipótese de que a segmentação atual (High Value) pode ser a causa, dado que médio/micro historicamente convertiam mais nesse canal.",
      "confianca": "media",
      "aplicavel_a": [
        "Outbound",
        "segmentação de base"
      ],
      "acao_sugerida": "Antes de ajustar segmentação Outbound, sempre comparar CPL e taxa de levantada por tier de escola (High Value vs médio vs micro) no histórico. Não assumir que High Value = melhor canal Outbound — o canal pode ter perfil de público diferente do canal de relacionamento.",
      "status": "ativo"
    },
    {
      "id": "insight102",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "operacao",
      "gatilho": "base WhatsApp 19 campos vs 2 utilizados",
      "insight": "A base de WhatsApp da Estante Mágica usa apenas 2 dos 19 campos de telefone disponíveis no CRM. A oportunidade de expansão de alcance está no próprio banco de dados, não em enriquecimento externo. Testar o envio utilitário para os campos não abordados e remover quem não responde é a forma mais rápida e barata de limpar e expandir a base simultaneamente.",
      "evidencia": "Vit identificou 19 campos de telefone; apenas 2 estão sendo usados nos disparos. Lili priorizou ampliar o raio antes de validar, com plano de teste via envio utilitário seguido de remoção dos não-respondentes.",
      "confianca": "alta",
      "aplicavel_a": [
        "WhatsApp",
        "base de contatos",
        "campanhas outbound"
      ],
      "acao_sugerida": "Sempre verificar cobertura de campos de telefone no CRM antes de contratar enriquecimento externo. Expansão interna de campos é mais rápida, mais barata e valida a base como efeito colateral do próprio disparo.",
      "status": "ativo"
    },
    {
      "id": "insight103",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "gatilho": "teste A/B retração presente exclusivo vs sem trabalho",
      "insight": "No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciprocidade supera o de facilidade operacional em 2,6x nesse público — que já conhece o produto e provavelmente tem objeção emocional, não operacional.",
      "evidencia": "Vit apresentou resultado do teste A/B de retração: 'presente exclusivo' CPL R$28, 'sem trabalho' CPL R$73. Resultado do dia 12/mar.",
      "confianca": "alta",
      "aplicavel_a": [
        "Retração",
        "copy WhatsApp",
        "copy e-mail"
      ],
      "acao_sugerida": "Para base de Retração, sempre usar ângulo de reciprocidade/presente como copy principal. Argumento funcional ('não dá trabalho') deve ser tratado como contorno de objeção secundária, não como gancho de abertura.",
      "status": "ativo"
    },
    {
      "id": "insight104",
      "data": "2026-03-12",
      "fonte": "Nath 12.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "insight": "HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de maior eficiência sendo sub-abastecido.",
      "evidencia": "HT PÚB Semanal: Tx Fechadas 235% da meta, Realizadas 4/11 (58% YTD), RR/SDR 1,33/2,29 (58%).",
      "confianca": "alta",
      "aplicavel_a": [
        "HT_PUB",
        "Renovacao"
      ],
      "acao_sugerida": "Em HT PÚB, alavanca de resultado é volume de prospecção (RR/SDR), não melhoria de discurso. Priorizar abastecimento de topo quando meta mensal estiver em risco.",
      "status": "ativo"
    },
    {
      "id": "insight106",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-29).",
      "evidencia": "Teste A/B Retração 12/03: 'presente exclusivo' CPL R$28, 'sem trabalho' CPL R$73 — apresentado por Vitória na daily.",
      "confianca": "alta",
      "aplicavel_a": [
        "Retracao"
      ],
      "acao_sugerida": "Adotar 'presente exclusivo' como copy padrão em toda comunicação de Retração; descontinuar variantes baseadas em ausência de esforço.",
      "status": "ativo"
    },
    {
      "id": "insight108",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Segmentação exclusiva em High Value pode estar deprimindo taxa de levantadas no Outbound: queda de 5 para 3,75 levantadas/disparo vs ano anterior (-25%), pois escolas médio e micro porte historicamente convertiam mais.",
      "evidencia": "Vitória apresentou queda de desempenho Outbound; hipótese levantada por Liliane e Vitória na daily 12/03.",
      "confianca": "media",
      "aplicavel_a": [
        "Outbound"
      ],
      "acao_sugerida": "Incluir segmento médio e micro porte em testes de Outbound ao lado do High Value para isolar se a queda é de segmentação ou de mercado.",
      "status": "ativo"
    },
    {
      "id": "insight109",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Formato de vídeo personalizado estilo Spotify Wrapped (dados reais da escola) funciona como mecanismo de relacionamento antes de renovação — cria antecipação sem pressão de compra.",
      "evidencia": "Liliane relatou sucesso histórico do formato; daily decidiu expandir para escolas em descarte/perda com disparo 16/03.",
      "confianca": "media",
      "aplicavel_a": [
        "Renovacao",
        "Anos Anteriores"
      ],
      "acao_sugerida": "Após validar resultado de 16/03, criar playbook do formato Spotify Wrapped para reuso em reativação e renovação.",
      "status": "ativo"
    },
    {
      "id": "insight110",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Copy de benefícios para Anos Anteriores performa melhor em escolas sem SDR atribuído — cold outreach WA é mais efetivo sem interferência de relacionamento prévio com SDR.",
      "evidencia": "Pedro Concy e Pimentel observaram na análise de disparos que copy benefícios funcionou especialmente bem em escolas sem SDR atribuído.",
      "confianca": "media",
      "aplicavel_a": [
        "Anos Anteriores"
      ],
      "acao_sugerida": "Segmentar base Anos Anteriores por presença/ausência de SDR atribuído e calibrar copy: benefícios para sem SDR, relacionamento para com SDR.",
      "status": "ativo"
    },
    {
      "id": "insight081",
      "data": "2026-03-11",
      "fonte": "Escuta de audio SDR 10/mar/26",
      "titulo": "SDR que cede a objecao de email sem reforcar valor da reuniao perde o agendamento",
      "descricao": "Padrao: SDR faz bom contorno inicial mas cede no final concordando em enviar pre-apresentacao sem reforcar que proposta personalizada e condicoes exclusivas so sao possiveis na reuniao. Ao ceder ao email deve: (1) desvalorizar conteudo do email (apresentacao superficial/generalizada), (2) reforcar que proposta real so na reuniao.",
      "categoria": "sdr",
      "status": "ativo",
      "evidencia": "Chamada de Mariana Nogueira analisada na sessao de escuta 10/mar/26. Leticia Montemor identificou o padrao como ponto negativo recorrente.",
      "acao_sugerida": "Incluir no discurso padrao: ao ceder ao email, desvalorizar o conteudo (generica, superficial) e reforcar que proposta personalizada e condicoes exclusivas so na reuniao com especialista."
    }
  ],
  "criticas_ativas": [
    {
      "id": "alerta056",
      "data": "2026-03-17",
      "titulo": "LT PART: receita 42% da meta com 10 dias úteis e ticket médio caindo",
      "critica": "LT PART hoje: 16/30 convertidas (53%) e R$42.244/R$98.649 em receita (42%). O alerta045 registrava 7 convertidas e R$24k. Houve avanço real (dobrou convertidas), mas a receita não acompanhou na mesma proporção — ticket médio implícito caiu de ~R$3.428 para ~R$2.640 por convertida. Com 10 dias úteis restantes, fechar os 14 convertidas restantes exige 1,4 convertidas/dia útil. Considerando que a base cadastrada agora tem 451 alunos (vs 272 anterior) e custo de disparo R$731, o potencial existe — mas o mix de escolas ativadas pode estar puxando o ticket para baixo.",
      "acao_sugerida": "Nath e Kaká: verificar composição das 16 convertidas (tamanho médio de escola, número de alunos por escola) e identificar se as escolas maiores da base de 451 ainda não foram trabalhadas — priorizá-las nas ações restantes da semana.",
      "prioridade": "critica",
      "dri": "Nath Ferreira",
      "status": "aberto",
      "nota_status": "Substitui e atualiza alerta045 com dados de 17/03 — LT PART avançou mas o problema de receita persiste e agora há evidência adicional de drift de ticket médio."
    },
    {
      "id": "alerta057",
      "data": "2026-03-17",
      "titulo": "HT PÚB Renovação: semana zerada em realizadas e fechadas",
      "critica": "HT PÚB registra 0 reuniões realizadas, 0 fechadas e RR/SDR 0 nesta semana — apesar de meta YTD de receita em 355% (verde). O zero semanal não é compensado pelo histórico positivo: com 10 dias úteis restantes e RR/SDR mensal de 1,50 vs meta 2,40 (63%), a frente precisa de abastecimento urgente de topo de funil. Uma segunda semana zerada comprometeria o RR/SDR mensal e potencialmente a meta de Realizadas mensais.",
      "acao_sugerida": "Pimentel ou DRI de HT PÚB: mapear causas do zero desta semana (agenda dos closers? ausência de leads qualificados? fila vazia?) e garantir pelo menos 5 reuniões agendadas para a semana de 18/03.",
      "prioridade": "critica",
      "dri": "Ana Paula Pimentel",
      "status": "aberto",
      "nota_status": ""
    },
    {
      "id": "alerta058",
      "data": "2026-03-17",
      "titulo": "Concorrência: meta de alunos mensais em 55% YTD com 10 dias úteis restantes",
      "critica": "Concorrência mensal: 810/2.963 alunos (55% YTD). O alerta042 registrava paradoxo RR/SDR saudável com alunos zerados na semana. Hoje a semana tem RR/SDR em 189% mas meta de alunos semanal em 0/897 (lag de contabilização confirmado). O problema central persiste: o volume mensal de alunos está abaixo de 50% de cumprimento efetivo (810 de meta implícita de ~1.480 para este ponto do mês). Com Realizadas mensais em 103% e RR/SDR em 111%, o gargalo continua sendo conversão RR→alunos (tamanho médio das escolas fechadas abaixo do esperado ou escolas com poucos alunos sendo priorizadas).",
      "acao_sugerida": "Nath: calcular número médio de alunos por escola fechada em Concorrência em março vs meta implícita (2.963/33 = ~89 alunos/escola) e identificar se há concentração de escolas pequenas no bolsão ativo.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberto",
      "nota_status": "Complementa alerta042, que identificou o paradoxo — este alerta adiciona a dimensão de ritmo mensal com 10 dias úteis restantes."
    },
    {
      "id": "alerta059",
      "data": "2026-03-17",
      "titulo": "LT PART: ritmo de convertidas insuficiente para bater meta de receita mesmo se volume for cumprido",
      "critica": "Com 16/30 convertidas (53%) e R$42.244/R$98.649 de receita (42%), fechar as 14 convertidas restantes ao ticket médio atual de R$2.640 geraria apenas R$79.204 — abaixo da meta de R$98.649. Para bater a meta de receita, o ticket médio das convertidas restantes precisaria ser R$4.029 (53% acima do atual). Isso significa que as escolas maiores da base de 451 alunos cadastrados precisam ser priorizadas ativamente nas próximas abordagens — não basta converter mais, precisa converter as certas.",
      "acao_sugerida": "Nath calcular ranking de escolas não-convertidas na base de 451 por tamanho (alunos) e Kaká/Vit priorizar essas escolas maiores no próximo disparo ou abordagem ativa — insumo para execução antes de 19/mar.",
      "prioridade": "critica",
      "dri": "Nath Ferreira",
      "status": "aberto",
      "nota_status": "Tarefa t179 cobre análise de ticket médio mas não inclui ranqueamento de escolas não-convertidas por tamanho para priorização ativa. Alerta complementar a t179."
    },
    {
      "id": "alerta060",
      "data": "2026-03-17",
      "titulo": "HT PÚB: pipeline de MKT com potencial R$61k sem reuniões realizadas na semana — handoff comercial ausente",
      "critica": "HT Pública registra 427 alunos cadastrados e potencial de R$61.488,30 em ações de MKT, mas o comercial entregou 0 realizadas e 0 fechadas na semana. A t187 (Pimentel mapear causa do zero e garantir 5 reuniões na semana de 18/03) está aberta, mas o dado de hoje confirma que o zero persiste em 17/03 — com apenas 2 dias úteis restantes nesta semana (17 e 18/03, terça e quarta), a meta de 5 realizadas na semana atual é matematicamente apertada. A semana de 18/03 começa amanhã, o que comprime o prazo de t187 a um único dia útil.",
      "acao_sugerida": "Pimentel confirmar hoje qual é o bloqueio específico (agenda de closers, fila de leads HT PÚB, priorização de outra frente) e acionar pelo menos 3 reuniões HT PÚB para amanhã 18/03 como piso mínimo.",
      "prioridade": "critica",
      "dri": "Ana Paula Pimentel",
      "status": "aberto",
      "nota_status": "Complementa alerta057 e t187 com dado atualizado de 17/03 e urgência de execução hoje."
    },
    {
      "id": "alerta061",
      "data": "2026-03-17",
      "titulo": "HT PÚB semanal: RR/SDR em 52% e Realizadas em 70% — segunda semana consecutiva de underperformance",
      "critica": "HT PÚB registra na semana: Realizadas 8/11 (70% YTD amarelo), RR/SDR 1,20/2,29 (52% da meta amarelo). O alerta057 registrava zero absoluto de realizadas na semana anterior. Houve recuperação parcial (saiu do zero para 8), mas o RR/SDR ainda está em 52% — abaixo do patamar mensal de 1,50 (que já está em 63% da meta de 2,40). O padrão de colapso semanal documentado no insight126 está se repetindo em ciclo: semana com zero seguida de semana com volume parcial insuficiente para recuperar o mensal.",
      "acao_sugerida": "Pimentel: com base no mapeamento solicitado na t187 (status semana 18/03), garantir que HT PÚB tenha pelo menos 11 realizadas na semana de 18/03 para recuperar o RR/SDR mensal para patamar amarelo superior (>75%). Prioridade de abastecimento de topo de funil para esta frente.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberto",
      "nota_status": "Parcialmente coberto pela t187, mas o dado atual (RR/SDR 52% semanal) adiciona evidência numérica nova que justifica alerta separado focado na recuperação do RR/SDR mensal."
    },
    {
      "id": "alerta045",
      "data": "2026-03-12",
      "titulo": "LT PART: 23% de convertidas e 24% de receita com 12 dias úteis restantes",
      "critica": "LT PART em 7/30 convertidas (23%) e R$24.000/R$98.649 em receita (24%). O alerta041 registrou esse dado para a semana passada; o documento de hoje confirma que não houve recuperação — os números são praticamente iguais. Com ~12 dias úteis restantes em março (supondo ~15 dias úteis no mês e 3 já executados), fechar os 23 convertidas restantes exigiria quase 2 convertidas por dia útil. A base cadastrada de 272 alunos e custo de disparo R$378 sugerem que a ação de disparo está ocorrendo, mas a conversão não está acompanhando. Isso é diferente do alerta041 (que focava em ausência de disparo) — aqui o disparo ocorreu e a conversão está baixa.",
      "acao_sugerida": "Kaká ou Vit: verificar se houve follow-up comercial nas 272 escolas com alunos cadastrados via LT PART que ainda não converteram — se o disparo gerou cadastro mas não gerou contato SDR, o funil está vazando entre marketing e comercial.",
      "prioridade": "alta",
      "dri": "Karina Machado",
      "status": "aberto",
      "nota_status": "2026-03-12: LT PART 7/30 convertidas (23%), R$24k/R$98k (24%). 272 alunos cadastrados indicam que o disparo gerou interesse, mas conversão não acompanhou. Alerta041 era sobre ausência de disparo; este é sobre gargalo de conversão pós-cadastro."
    },
    {
      "id": "alerta046",
      "data": "2026-03-12",
      "titulo": "Queda de performance Outbound sem diagnóstico formal",
      "critica": "Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análise formal nem plano de ação.",
      "acao_sugerida": "Vitória analisar composição da base Outbound 2025 vs 2026 (porte, SDR atribuído, segmento) e apresentar hipótese validada até 13/03.",
      "prioridade": "alta",
      "dri": "Vitória",
      "status": "aberto",
      "nota_status": "",
      "evidencia": "Mar/12 confirmado: 2.625 base, 5 lev (0.19%), CPL R$121,72 — pior CPL do historico de disparos Outbound. Padrao consolidado em 3 meses consecutivos. Ver insight115.",
      "ultima_atualizacao": "2026-03-13T08:51:54.377989"
    },
    {
      "id": "alerta047",
      "data": "2026-03-12",
      "titulo": "Inconsistência na contabilização de escolas convertidas",
      "critica": "Pimentel sinalizou problema de contabilização de escolas convertidas ao final da daily — sem DRI ou prazo definidos. Distorce todas as métricas de meta.",
      "acao_sugerida": "Pimentel mapear qual sistema/campo gera inconsistência na contagem de convertidas e acionar tecnologia se necessário até 16/03.",
      "prioridade": "alta",
      "dri": "Pimentel",
      "status": "aberto",
      "nota_status": ""
    },
    {
      "id": "alerta039",
      "data": "2026-03-11",
      "titulo": "Numero WA institucional bloqueado pela Meta durante teste SDR — ativo de contato comprometido",
      "critica": "Numero utilizado no teste de ligacoes WA com 30 escolas sofreu bloqueio na Meta, possivelmente por denuncia. Nao esta claro se e o numero principal ou temporario. Se for o principal, todos os disparos, campanhas e contatos ativos estao em risco.",
      "acao_sugerida": "Luana confirmar hoje se o numero bloqueado e o principal ou temporario. Se for o principal: Pedro e Vitoria acionam recuperacao junto a Meta imediatamente. Documentar numero afetado e isolar das campanhas ate recuperacao confirmada.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberto",
      "nota_status": "Identificado via Mensagem da Lua.pdf em 11/mar/2026"
    },
    {
      "id": "alerta040",
      "data": "2026-03-11",
      "titulo": "Retracao semanal em colapso (2/14 RRs, 29% RR/SDR) e Outbound abaixo (6/20)",
      "critica": "Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao, risco de marco fechar abaixo.",
      "acao_sugerida": "Vitoria executar WA amanha 8h com copy vencedor do A/B. Se ate quinta 14/03 sem recuperacao significativa, Pimentel acionar reforco de SDR ou redirecionamento de capacidade.",
      "prioridade": "critica",
      "dri": "Vitoria Riente",
      "status": "aberto",
      "nota_status": "A/B email disparado 11/03. WA previsto amanha 8h."
    },
    {
      "id": "alerta042",
      "data": "2026-03-11",
      "titulo": "Concorrencia paradoxo: RR/SDR 102% mas zero alunos cadastrados na semana",
      "critica": "Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes.",
      "acao_sugerida": "Nath investigar causa do gap RR/SDR vs alunos em Concorrencia na semana 11/03. Diagnostico ate sexta-feira 13/03.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberto",
      "nota_status": "Tarefa de investigacao criada (t161)"
    },
    {
      "id": "alerta036",
      "data": "2026-03-10",
      "titulo": "Decisão de WA utilitário pré-ligação sem DRI e sem protocolo de teste",
      "critica": "Pedro propôs envio de WA utilitário antes de cada ligação SDR. Ana Paula levantou risco de saturação. Lili não concluiu a deliberação. A daily encerrou sem decisão formal, sem DRI e sem definição de teste controlado. Se alguém implementar sem protocolo, pode comprometer o canal WA que já está em uso pela campanha LT e pelo Cerco Mágico.",
      "acao_sugerida": "Pedro ou Lili definir até 12/mar: (1) se o WA utilitário será testado ou arquivado, (2) se testado — DRI, frequência máxima por contato, tamanho da amostra e KPI de sucesso/fracasso.",
      "prioridade": "alta",
      "dri": "Pedro Concy",
      "status": "aberto",
      "nota_status": "DRI atualizado para Pedro em 11/mar/2026. Pedro assume decisao: (1) testar ou arquivar WA utilitario pre-ligacao SDR, (2) se testar: definir DRI execucao, frequencia, amostra e KPI."
    },
    {
      "id": "alerta037",
      "data": "2026-03-10",
      "titulo": "Base de Concorrência segmentada (+100 alunos) restrita a uma SDR — expansão deliberada mas sem DRI",
      "critica": "A daily decidiu ampliar a base de Concorrência segmentada (acima de 100 alunos) para as SDRs com melhor performance, em vez de mantê-la restrita a uma única SDR. Decisão tomada, mas não há DRI nomeado para executar a redistribuição nem prazo definido. Sem execução, a decisão não tem efeito na média de alunos de março.",
      "acao_sugerida": "Ana Paula Pimentel executar redistribuição da base +100 alunos de Concorrência entre as 2-3 melhores SDRs até 12/mar, validando performance prévia com Nath antes da redistribuição.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberto",
      "nota_status": "Decisão tomada na daily de 10/mar/2026 sem tarefa gerada"
    },
    {
      "id": "alerta038",
      "data": "2026-03-10",
      "titulo": "Custo da Revista e mala direta desagregado — realizado não atualizado no orçamento",
      "critica": "Vit informou custo total de R$11.500 (revista + carta de dezembro) mas Lili pediu separação entre custo de produção e custo de envio da revista especificamente, além de atualização do realizado no controle de orçamento. Sem essa separação, o orçamento de marketing do Cerco Mágico (que inclui nova revista) não tem referência de custo unitário confiável.",
      "acao_sugerida": "Vitória separar custo de produção e envio da revista de dezembro e atualizar o realizado no controle de orçamento de marketing até 12/mar.",
      "prioridade": "media",
      "dri": "Vitória",
      "status": "aberto",
      "nota_status": "Solicitado por Lili na daily de 10/mar/2026"
    },
    {
      "id": "alerta034",
      "data": "2026-03-09",
      "titulo": "AA taxa de fechamento semanal em 3% — possível queda na conversão do closer",
      "critica": "Meta Aquisição 09/03: AA Fechada/Realizadas semanal = 3%/57% = 52% da meta. Isso significa que de 27 RRs realizadas nesta semana, praticamente nenhuma escola fechou. Pimentel identificou Marcele como closer com desempenho ruim na semana anterior. Ainda é semana 1 e pode ser ruído estatístico, mas se se repetir na semana 2, o impacto no bolsão de AA e na receita de março é significativo.",
      "acao_sugerida": "Pimentel monitorar taxa de fechamento AA semana a semana. Se taxa se mantiver abaixo de 40% na semana de 09/mar, diagnóstico pontual com Marcele até 13/mar. Não alterar processo antes de confirmar padrão em 2 semanas consecutivas.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta",
      "fonte": "Meta Aquisição 09/03/2026"
    },
    {
      "id": "alerta032",
      "data": "2026-03-08",
      "titulo": "HT PART Renovação encerrou semana com déficit irrecuperável — 79% RR/SDR",
      "critica": "A semana de 03-06/mar encerrou com HT PART Renovação em 79% do RR/SDR semanal. Na daily 06/mar, as 22 RRs necessárias no último dia eram matematicamente impossíveis. O deficit da semana vai acumular em março se não houver correção imediata na semana de 09/mar. É o maior baldinho de Renovação e está sistematicamente abaixo da meta.",
      "acao_sugerida": "Pimentel analisa base HT PART antes de segunda (t100). Nath executa disparo MKT HT PART na segunda 09/mar (t100). Nath entrega visão do funil de renovação (t070) até 10/mar para diagnóstico de onde está trancando.",
      "prioridade": "critica",
      "dri": "Ana Paula Pimentel",
      "status": "aberta",
      "fonte": "Daily Gestão Comercial 06/03/2026 + análise sessão Claudete 08/03",
      "nota_status": "09/03: RR/SDR HT PART semana 1 = 1,32/1,60=83%. Disparo HT PART 5-30k iniciado por Vitória hoje (t100 concluído). Análise Pimentel confirmada. Semana de recuperação em curso. Monitorar RR/SDR diariamente para avaliar se disparo gerou volume."
    },
    {
      "id": "alerta033",
      "data": "2026-03-08",
      "titulo": "Calix perdendo efeito em AA e Retração — enriquecimento previsto para maio, Cerco começa em março",
      "critica": "Daily 06/03 confirmou que o Calix está perdendo efetividade nas bases de AA e Retração. O enriquecimento de base estava planejado para maio. O Cerco Mágico começa em março com as duas frentes de maior ROI histórico (AA: insight002) operando com ferramenta degradada. Gap de 2 meses sem solução.",
      "acao_sugerida": "Luana avaliar antecipação do enriquecimento de base para março/abril — não pode esperar maio com o Cerco em execução. Alternativa: enriquecimento pontual das 130 escolas AA isoladas por Pimentel (sem contato em 2026) como teste prioritário antes do disparo. DRI: Luana.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberta",
      "fonte": "Daily Gestão Comercial 06/03/2026 + análise sessão Claudete 08/03"
    },
    {
      "id": "alerta029",
      "data": "2026-03-03",
      "critica": "Processo de Boas-Vindas em risco crítico. Lili alertou na daily 03/03 que falha nessa etapa pode comprometer metade da receita anual. Escolas fechadas que não progridem no onboarding viram receita perdida. Time ainda sem acompanhamento estruturado do processo. Nath solicitada a criar controle.",
      "dri": "Liliane Mathias",
      "prioridade": "critica",
      "acao_sugerida": "Lili e Nath criarem acompanhamento semanal de Boas-Vindas (t082). Pimentel levantar volume com Maria Laísa (t084). Avaliar se enriquecimento pode ser suspenso temporariamente para alocar pessoal.",
      "status": "aberta",
      "fonte": "Daily Gemini 03/03/2026"
    },
    {
      "id": "alerta030",
      "data": "2026-03-03",
      "critica": "HT PÚB Renovação com zero fechamentos nesta semana (Tx fechadas/realizadas = 0). Duas reuniões realizadas, nenhuma convertida. Segmento tem RR/SDR de 2,40 (acima da meta), mas sem conversão de fechamento na semana de 03/03. Pode ser início de mês, mas merece monitoramento imediato.",
      "dri": "Karina Machado",
      "prioridade": "alta",
      "acao_sugerida": "Kaka verificar o que aconteceu nas 2 RRs de HT PÚB desta semana: objeção de fechamento, missing follow-up ou timing? Acompanhar diariamente até a semana fechar.",
      "status": "aberta",
      "fonte": "Daily Meta Aquisição 03/03/2026",
      "nota_status": "08/03: HT PUB bateu meta de RR na semana de 03-06/mar (daily 05-06/03). Monitorar conversão de fechamento na semana de 09/mar."
    },
    {
      "id": "alerta025",
      "data": "2026-03-02",
      "critica": "Concorrencia abriu marco com 45% de fechadas/realizadas vs 58% em fevereiro - queda de 13pp sem causa documentada. Com 1 SDR a menos e bolsao herdado de fev, risco de degradacao continuada.",
      "dri": "Ana Paula Pimentel",
      "prioridade": "critica",
      "acao_sugerida": "Pimentel entregar doc de investigação histórica da queda (t103, prazo 13/mar). Verificar: alunos/escola em Concorrência, tx fechamento pós-RR março vs fevereiro, composição carry-over vs novas. A/B copy 'diminuição de trabalho' confirmado (insight070) — copy digital resolvida. Problema pode estar no pós-RR.",
      "status": "aberta",
      "nota_status": "08/03: A/B copy resolvido (insight070). Meta de alunos Concorrência ainda em 13%. Investigação histórica em andamento (t103). Alerta mantido."
    },
    {
      "id": "alerta026",
      "data": "2026-03-02",
      "critica": "HT PART Renovacao com RR/SDR de 1,60 vs meta de 2,0 - gap de 0,40pp. Situacao piorou: daily 06/03 mostra 79% RR/SDR semanal com 22 RRs necessarias no ultimo dia — impossivel de recuperar. Semana encerrada em deficit.",
      "dri": "Ana Paula Pimentel",
      "prioridade": "critica",
      "acao_sugerida": "Pimentel analisa base HT PART antes de segunda (t100) para direcionar disparo MKT 09/mar (t100). Nath executa disparo. Semana de 09/mar é a janela de recuperação.",
      "status": "aberta",
      "nota_status": "09/03: Disparo HT PART Renov 5-30k (etapas SDR + descarte + perdido, exceto críticas) iniciado por Vitória — ação do dia na Meta Aquisição. RR/SDR HT PART semana 1: 1,32/1,60=83%. Realizadas: 38/59=65% (semana 1 de 4). Meta receita comercial 251% YTD. Semana de recuperação em curso — monitorar diariamente."
    },
    {
      "id": "alerta023",
      "data": "2026-02-27",
      "titulo": "WA pessoal da Lili bloqueado — canal de ativação 1-a-1 sem protocolo de contingência",
      "critica": "Número da Lili bloqueado por 24h após Operação Lili Doce. Chip novo tem mesmo risco de bloqueio por volume. Operação de hoje (48 escolas) está em risco de canal. Sem rotação de chips ou limite diário documentado, o problema vai se repetir em cada operação de ativação em escala.",
      "acao_sugerida": "Pedro compra chip temporário hoje (t058). Vit testa Blip como aviso de mimo (t062). Definir protocolo: máximo de mensagens por número por dia, chips em rodízio, Blip para informativo e WA para pedido de lista.",
      "prioridade": "alta",
      "dri": "kaka",
      "status": "aberta"
    },
    {
      "id": "alerta024",
      "data": "2026-02-27",
      "titulo": "Saída de 3+ pessoas de Renovação em fevereiro — impacto em capacidade de março sem análise",
      "critica": "Renovação perde 3 pessoas + Lari este mês (além de Isabele e Poli para Relacionamento). Time está em 77% da meta empresa. Nath expressou preocupação explícita com estabilidade. Nenhuma análise de impacto em RR/SDR de março foi feita ainda.",
      "acao_sugerida": "Nath recalcula headcount real e impacto em RR/SDR esperado para março (t063). Trazer para Pedro na segunda. Se houver gap crítico de capacidade, Pedro decide sobre aceleração de contratação.",
      "prioridade": "alta",
      "dri": "nath",
      "status": "aberta"
    },
    {
      "id": "alerta018",
      "data": "2026-02-26",
      "titulo": "Copy de Outbound (playlist emocional) tem CPL 7,4x acima do benchmark — reformulação urgente antes do próximo ciclo",
      "critica": "Outbound Playlist 23/02: R$721,44 para 2 levantadas. CPL R$360,72 vs benchmark R$48,60. Copy de 'experiência emocional do filho com trilha sonora' gera cliques (18 = 1,35%) mas não levantadas (2 = 0,15%). Ratio 9:1 clique:levantada confirma: o conteúdo ressoa como entretenimento, não como proposta comercial. Se o próximo ciclo de Outbound repetir essa abordagem, estamos queimando orçamento de forma previsível.",
      "acao_sugerida": "Luana e Vitória: desenvolver nova copy de Outbound com argumento de negócio (ROI, diferenciação, exclusividade) antes do próximo disparo. Ver insight043 para diretriz. Nenhum disparo de Outbound com copy emocional/playlist enquanto nova abordagem não for testada.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberta",
      "evidencia": "Mar/03 Playlist Renovacao Publica e Particular: 0 levantadas (objetivo = Levantada). Confirma que Playlist nao funciona para Renovacao como oferta de levantada. Ver insight111.",
      "ultima_atualizacao": "2026-03-13T08:51:54.377989"
    },
    {
      "id": "alerta020",
      "data": "2026-02-26",
      "titulo": "Blip ligações — risco de spam sistêmico: gestora nega → contato bloqueado permanentemente",
      "critica": "Identificado na daily 26/02: Blip para ligações exige confirmação da gestora antes de ligar. Se ela nega, o contato é marcado como spam permanentemente. Isso pode estar destruindo silenciosamente a base de contatos antes de qualquer abordagem real. Teste com SDR externa em andamento mas resultado ainda desconhecido. Enquanto não houver validação, risco real de dano irreversível à base.",
      "acao_sugerida": "Pimentel/Nath: suspender uso de Blip para ligações até resultado do teste externo. Avaliar impacto retroativo: quantos contatos já foram bloqueados. Definir protocolo de uso antes de reativar.",
      "prioridade": "critica",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta021",
      "data": "2026-02-26",
      "titulo": "Time de Concorrência perde 1 pessoa em março — base recomeça do zero com capacidade reduzida",
      "critica": "Identificado na daily 26/02: 1 pessoa do time de Concorrência (3 no total) não será efetivada. Sai no mês seguinte. Além da redução de capacidade, a desmotivação pode contaminar outra colega do time. Em março, a base de Concorrência recomeça do zero com time menor e possivelmente desmotivado.",
      "acao_sugerida": "Pimentel avaliar impacto na meta de Concorrência de março e ajustar expectativa. Considerar medidas de gestão para não contaminar o time restante. Planejar onboarding/recomposição se necessário.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta012",
      "data": "2026-02-25",
      "titulo": "Goto aparece como spam — taxa de contato AA contaminada por infraestrutura",
      "critica": "Chamadas da Goto aparecem como spam nos telefones das gestoras. Testado pela própria Lua em 24/02. Isso significa que toda a análise de taxa de contato de AA feita até hoje pode estar subestimando o problema real — o bloqueio é de infraestrutura, não de lista ou copy. Escolas que não atenderam podem não ter visto como 'não interesse', mas como spam bloqueado automaticamente.",
      "acao_sugerida": "Lua testar hoje 1 SDR ligando de fora da Goto (celular pessoal/número alternativo) para escolas AA que não responderam. Comparar taxa de contato vs Goto. Nath isolar métricas: contatos via WhatsApp vs Goto, taxa de cada. Resultado em D+2.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "em_execucao",
      "atualizacao_25_02": "Teste confirmado para 26/02: Tati isolada para ligar fora da Goto. Lili confirmou com Lua às 19:15 via Google Chat. Resultado esperado em D+1 (26/02).",
      "nota_status": "02/03: Nath ativou Bina na GOT. Investigacao spam com Lua em andamento (t027)."
    },
    {
      "id": "alerta013",
      "data": "2026-02-25",
      "titulo": "Copy da caneca sem CTA de condicionamento — expectativa errada na escola",
      "critica": "Uma escola foi à RR com o Closer esperando a caneca como brinde garantido, não como benefício condicional à adesão. A copy atual não deixa claro que a escola precisa agir para receber o mimo. Isso enfraquece o argumento do Closer no fechamento e pode estar acontecendo em mais escolas silenciosamente.",
      "acao_sugerida": "Vitória/Kaka revisar copy do disparo de 25/02 antes de enviar: incluir CTA explícito de condicionamento ('para garantir a sua caneca, basta...'). Regra permanente: todo disparo de mimo físico deve ter o condicionamento explícito na mensagem.",
      "prioridade": "alta",
      "dri": "Karina Machado",
      "status": "aberta"
    },
    {
      "id": "alerta014",
      "data": "2026-02-25",
      "titulo": "Script SDR com 'como foi?' ainda ativo para escolas com feedback negativo",
      "critica": "A pergunta 'como foi sua experiência?' está no discurso SDR de 2025 e 2026. Para escolas com feedback negativo registrado no card, ela abre objeção imediata que o SDR não consegue reverter — e que o Closer vai herdar na reunião. A investigação de Bebel documentou isso em dois ciclos consecutivos sem que o script fosse corrigido.",
      "acao_sugerida": "Lua implementar filtro por histórico de feedback antes do contato SDR: escola com flag negativo não recebe a pergunta 'como foi?' — SDR abre com Instagram ou argumento de benefícios diretamente. Treinamento pontual com supervisores, não reciclagem geral do script.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberta"
    },
    {
      "id": "alerta015",
      "data": "2026-02-25",
      "titulo": "Email pós-reunião do Closer é brochure — não prepara escola para aprovação interna",
      "critica": "O template atual de email pós-RR apresenta a Estante Mágica do zero para uma escola que acabou de fechar. Não inclui argumentos para a coord apresentar ao diretor/financeiro que não participou da reunião. Isso cria um vácuo no momento mais crítico da aprovação interna — e pode estar contribuindo para o gap de bolsão (fechada sem converter).",
      "acao_sugerida": "Pimentel reescrever template de email pós-RR como kit de aprovação interna: resumo personalizado da conversa + três argumentos para o diretor/financeiro + vídeo de envio por foto/áudio + oferta com prazo. Brochure genérico vira anexo opcional. Implementar antes do próximo ciclo de reuniões de AA.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta016",
      "data": "2026-02-25",
      "titulo": "LGPD como bloqueio de conversão emergindo — 3 casos simultâneos sem processo padronizado",
      "critica": "Três escolas simultâneas se recusaram a compartilhar dados de alunos por questão de LGPD em 25/02. Cada caso está sendo resolvido individualmente (1 em Tech, 1 negociando acesso direto, 1 com nova RR). Sem fluxo padronizado, cada novo caso consome tempo de Wydi/Pimentel e pode travar a conversão por dias. Se o volume escalar, vira gargalo sistêmico de bolsão.",
      "acao_sugerida": "Pimentel mapear os 3 casos ativos e criar fluxo de resolução padrão: (1) escola quer subir ela mesma → protocolo Tech já; (2) escola recusa categoricamente → escalada com argumento jurídico/contratual. Prazo: antes de março. Incluir script de prevenção para o Closer usar na RR.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta017",
      "data": "2026-02-25",
      "titulo": "24% das levantadas de AA descarte são registros 'Duplicada' — base inflando resultados",
      "critica": "No resultado final de c003 (caneca AA 25/02), 6 de 25 levantadas (24%) vieram de registros classificados como 'Duplicada' na base. Se são registros duplicados da mesma escola, o número real de levantadas únicas é 19, não 25 — e o CPL está subestimado em ~32%. Enquanto não houver limpeza, todo relatório de campanha de AA descarte reporta resultado inflado.",
      "acao_sugerida": "Vitória identificar se as 6 'Duplicada' são escolas repetidas no sistema ou um status de descarte diferente. Se forem duplicatas de registro, limpar a base antes do próximo ciclo de disparos de AA e ajustar número oficial de levantadas de c003.",
      "prioridade": "alta",
      "dri": "Vitória Riente",
      "status": "aberta"
    },
    {
      "id": "alerta001",
      "data": "2026-02-24",
      "titulo": "SDR 12%: efetividade a 2,5x abaixo da meta",
      "critica": "Efetividade SDR precisa ser atualizada no painel para validar o cenário real. Sem esse dado, o diagnóstico de capacidade fica cego.",
      "acao_sugerida": "Nath atualizar a efetividade SDR no dashboard hoje e confirmar fonte (data e período).",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberta",
      "nota_status": "09/03: RR/SDR por baldinho (Meta Aquisição 09/03): HT PART 1,32/1,60=83%, HT PUB 1,80/2,40=75%, AA 0,86/0,75=115%✅, Concorrência 0,55/0,50=110%✅, Retração 0,43/0,64=68%, Novas 0,32/0,46=77%. AA e Concorrência acima da meta; Retração e HT persistem abaixo. Efetividade global heterogênea — alerta mantido."
    },
    {
      "id": "alerta004",
      "data": "2026-02-24",
      "titulo": "Retração semana: RR/SDR em 40% — março começa em débito",
      "critica": "O mês de fevereiro de Retração está verde (107% RR/SDR), mas a semana de 24/02 está em 0,20/0,50 (40%) no Baldinho Retração. O resultado mensal está sendo sustentado por estoque de semanas anteriores. Se esse ritmo se repetir em março, o mês começa morto.",
      "acao_sugerida": "Nath verificar esforço de SDR em Retração nessa semana: é inércia do time, Ax ou decisão de manter o 0,5 por conta de meta já batida? Definir ritmo mínimo para semana que vem.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberta",
      "nota_status": "09/03: Retração RR/SDR 0,43/0,64=68% da meta YTD. Tx fechadas/realizadas: 50%/62%=81%. Realizadas: 10/56=78% YTD. Meta alunos 1.088/4.355=110%✅. Melhora vs 40% de fev mas ainda estruturalmente abaixo de meta. Nath não entregou diagnóstico de causa. Alerta mantido."
    },
    {
      "id": "alerta005",
      "data": "2026-02-24",
      "titulo": "Renovação LT Part: RR/SDR travado em 1,42 há 5 dias",
      "critica": "De 19/02 a 24/02, o RR/SDR da base LT Part ficou em 1,42 — mesmo número, todos os dias. Ou os dados não estão sendo atualizados corretamente, ou o esforço está estagnado. Meta é 2,0.",
      "acao_sugerida": "Nath verificar se o dado está sendo registrado corretamente. Se sim, identificar qual ação específica pode mover o RR/SDR LT antes do fechamento do mês.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberta",
      "nota_status": "09/03: LT PART em 3/30 convertidas = 10% da meta mensal. Meta marketing LT Part: R$8.945/R$98.649 = 9%. A frente inteira está em risco crítico — não apenas o RR/SDR, mas as convertidas e a receita de marketing. Ação de MKT urgente para LT PART não apareceu nas ações do dia de 09/03. Alerta escalado em urgência."
    },
    {
      "id": "alerta006",
      "data": "2026-02-24",
      "titulo": "Ativação bolsão em 61% da meta — receita fechada não está virando bolsão",
      "critica": "A conversão para Closer está acima da meta, mas a ativação (bolsão) está em 61%. O esforço de SDR e Closer está funcionando — o gargalo é o último elo da cadeia: escola fecha e não converte para bolsão. Essa é a receita que está 'dentro de casa' e não realizada. Com 4 dias úteis até 28/fev, 40 mimos devem ser enviados hoje para destravar esse funil.",
      "acao_sugerida": "Karina garantir envio dos 40 mimos para bolsão hoje (via Pix com Rafa se cartão/iFood travar). Confirmar status de cada envio no D+1. Meta: 10 em 10 agendamentos de bolsão recebem mimo antes do contato de ativação.",
      "prioridade": "critica",
      "dri": "Karina Machado",
      "status": "aberta",
      "atualizacao_25_02": "Mimos enviados: 27 (Pimentel) + 28 (Wydi) = ~55 no dia. Taxa de reversão de sumiço: 20% (4/20). Dia comprometido por 2 de 5 ativadores ausentes (40% capacidade) + parada para alinhamento operacional. 10 retornos programados para 26/02 com gestão/secretaria. Benchmark registrado: insight039."
    },
    {
      "id": "alerta007",
      "data": "2026-02-24",
      "titulo": "Tags Blip/HubSpot inválidas — medição de levantadas de campanha inflada em até 4x",
      "critica": "Tag de marketing (rastreia todas as escolas que receberam disparo) está sendo usada como proxy de levantadas. Resultado: número de 54 levantadas da caneca 23/02 é não confiável — sobreposição com ações anteriores infla o dado. Todo ROI de campanha calculado com esse número é inválido. Decisões de budget, copy e segmentação baseadas nesse número estão contaminadas.",
      "acao_sugerida": "Vitória criar tag separada 'disparo_recebido' (distinta da tag Heróis de levantada confirmada) antes do próximo disparo. Revisar retroativamente levantadas das últimas campanhas usando apenas tag Heróis como denominador. Nunca reportar tag de marketing como proxy de levantadas.",
      "prioridade": "critica",
      "dri": "Vitória Riente",
      "status": "aberta"
    },
    {
      "id": "alerta009",
      "data": "2026-02-24",
      "titulo": "Fluxo de atribuição de levantadas inexistente — leads quentes perdidos sistematicamente",
      "critica": "27 escolas de renovação levantaram a mão em 23/02 e não receberam contato no mesmo dia. Tickets Blip fechados antes do SDR entrar em contato. O processo atual de distribuição geral automática não está funcionando. Cada lead quente não atendido em 2h tem probabilidade de conversão drasticamente reduzida.",
      "acao_sugerida": "Vitória criar filas Blip por baldinho hoje. Pimentel fornecer nomes dos supervisores por baldinho até 10h. Supervisor com acesso ao portal Blip prioriza atribuição 8h-9h. Confirmar funcionamento antes do disparo de 25/02.",
      "prioridade": "critica",
      "dri": "Vitória Riente",
      "status": "aberta"
    },
    {
      "id": "alerta011",
      "data": "2026-02-24",
      "titulo": "Outbound WhatsApp com 0,15% de levantadas",
      "critica": "O disparo Outbound teve 2 levantadas em 1.336 entregues (0,15%). Isso é desempenho estruturalmente baixo e indica falha de segmentação, lista ou copy. Continuar disparando nessa base sem correção consome orçamento e gera custo de oportunidade.",
      "acao_sugerida": "Vitória revisar segmentação e copy do Outbound; testar micro-lote com lista qualificada antes de novo disparo em massa.",
      "prioridade": "alta",
      "dri": "Vitoria",
      "status": "aberta"
    },
    {
      "id": "alerta050",
      "titulo": "Impulsionar Fevereiro estourou 91% do orcamento (R$18.312 vs R$9.607 orcado) sem registro de aprovacao",
      "tema": "campanha",
      "data_criacao": "2026-03-13",
      "status": "aberto",
      "prioridade": "alta",
      "dri": "Vitoria",
      "evidencia": "Aba Orcamentos Mes a Mes: Fev Impulsionar orcado R$9.606,50, realizado R$18.311,79, saldo -R$8.705,29. Marco: R$2.100,75 de R$9.606,50 (22% usado). Sem registro de aprovacao para o estouro de fevereiro.",
      "acao_sugerida": "Pedro e Vitoria: definir teto semanal para Impulsionar ou exigir aprovacao de Pedro para qualquer valor acima do orcado. Revisar o que gerou o estouro de R$8.705 em fevereiro e avaliar se houve ROI equivalente.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026"
    },
    {
      "id": "alerta051",
      "tema": "rampando_visibilidade_zero",
      "critica": "Pimentel depende do feedback da Taises para acompanhar o desempenho do time de Rampando isoladamente. Sem visibilidade separada, e impossivel ajustar indicadores do Rampando em tempo real e o efeito de arrasto no RR/SDR geral de Novas continua invisivel.",
      "evidencia": "Daily 13/03: Pimentel declarou dependencia da Taises. Nath numbers: RR/SDR Novas geral 0,33/0,46 (79%). Sem breakout de Rampando vs senior no documento.",
      "acao_sugerida": "Nath ou Pimentel criar relatorio semanal separado para time de Rampando (RR/SDR, fechadas, realizadas) entregue toda segunda-feira antes da daily — sem depender de Taises como intermediaria.",
      "dri": "Ana Paula Pimentel",
      "prioridade": "alta",
      "status": "aberto",
      "data_registro": "2026-03-13"
    },
    {
      "id": "alerta052",
      "tema": "retracao_enriquecimento_prazo",
      "critica": "Enriquecimento das 66 escolas prioritarias de Retracao depende do time de Dados para formatacao, prazo estimado quarta 18/03. Com RR/SDR semanal em 51% e bolsao com apenas 34 oportunidades, qualquer atraso inviabiliza acao desta semana.",
      "evidencia": "Daily 13/03: Lili decidiu enriquecer 66 escolas. Vitoria confirmou dependencia de Dados. Nath numbers: Retracao semanal realizadas 7/14 (64% meta), bolsao 34 oportunidades.",
      "acao_sugerida": "Vitoria confirmar com time de Dados hoje (13/03) a viabilidade da entrega na quarta 18/03. Se entrega em risco, escalar para Pedro hoje EOD para viabilizar alternativa.",
      "dri": "Vitoria",
      "prioridade": "alta",
      "status": "aberto",
      "data_registro": "2026-03-13"
    },
    {
      "id": "alerta053",
      "tema": "outbound_cpl_alto_sem_decisao",
      "critica": "CPL do Outbound acima de R$100 (Mar/12: R$121,72, 5 levantadas em 2.625 base HV). Analise de composicao de base 2025 vs 2026 (t174, prazo original 13/03) nao foi entregue. Nenhuma decisao de suspensao ou roteamento alternativo foi tomada.",
      "evidencia": "Daily 13/03: CPL Outbound declarado acima de R$100. t174 prazo 13/03 nao cumprido. alerta046 ja registrado — esta critica escala o contexto.",
      "acao_sugerida": "Vitoria entregar analise de composicao Outbound 2025 vs 2026 ate segunda 16/03. Resultado deve incluir: CPL por tier, taxa de levantada por regiao, comparacao com 2025.",
      "dri": "Vitoria",
      "prioridade": "alta",
      "status": "aberto",
      "data_registro": "2026-03-13"
    },
    {
      "id": "alerta054",
      "tema": "revista_arte_critico",
      "critica": "Arte da revista do Cerco Magico ainda nao fechada (t088, prazo 14/03). Karina contactou dois designers hoje (13/03), mas arte precisa estar aprovada para envio a grafica. Sem arte fechada ate segunda 16/03 no maximo, entrega em abril fica em risco.",
      "evidencia": "Daily 13/03: Vitoria aguarda orcamento da grafica. Karina confirmou que designer seria contactado hoje. t088 em PENDENTE desde 08/03.",
      "acao_sugerida": "Karina confirmar ate 14/03 se pelo menos um dos designers aceitou e quando entrega a arte. Se nenhum disponivel, escalar para Pedro imediatamente.",
      "dri": "Karina Machado",
      "prioridade": "critica",
      "status": "aberto",
      "data_registro": "2026-03-13"
    },
    {
      "id": "alerta055",
      "tema": "webinar_antonia_sem_briefing",
      "critica": "Webinar com Antonia Burk confirmado para a primeira semana de abril, mas Pedro e Karina ainda nao enviaram briefing a Pimentel (datas, tema, formato). Com menos de 3 semanas para o evento, o atraso comprime producao e divulgacao.",
      "evidencia": "Daily 13/03: proxima etapa explicita — Pedro e Karina enviam briefing ate a proxima semana. Evento confirmado para primeira semana de abril.",
      "acao_sugerida": "Pedro e Karina enviar briefing do webinar (datas, tema, formato, speaker) para Pimentel ate segunda 16/03.",
      "dri": "Pedro Concy",
      "prioridade": "media",
      "status": "aberto",
      "data_registro": "2026-03-13"
    }
  ],
  "indices_digest": {
    "temas_disponiveis": [
      "sdr",
      "base",
      "rr_sdr",
      "geral",
      "renovacao",
      "copy",
      "concorrencia",
      "outbound",
      "funil",
      "retracao",
      "campanha",
      "whatsapp",
      "anos_anteriores",
      "canal",
      "novas",
      "todos",
      "comportamento",
      "baldinho",
      "oferta",
      "bolsao_ativacao",
      "copy_e_mensagem",
      "operacoes_comerciais",
      "operacao",
      "processo_sdr",
      "performance",
      "renovacao_lt",
      "lt_part",
      "ht_pub",
      "bolsao",
      "base_concorrencia",
      "aa_fechadas",
      "wpp_disparos",
      "timing",
      "segmentacao_de_base",
      "segmentacao",
      "modelo_operacional",
      "lt_publica",
      "escolas_saturadas",
      "copy_escrita",
      "bolsao_2025",
      "time_de_vendas",
      "ticket_medio",
      "sdr_cadencia_de_contato",
      "risco",
      "renovacao_ht_part",
      "qualificacao_de_base",
      "protocolo_de_fechamento",
      "pitch_closer",
      "operacoes_manuais",
      "operacional",
      "mkt_renovacao",
      "meta",
      "marketing",
      "ht_publica",
      "handoff_mkt_comercial",
      "funil_novas_escolas",
      "ferramenta",
      "estrategia_de_ativacao_de_base",
      "escolas_saturadas_alto_valor",
      "escolas_fechadas_nao_convertidas",
      "copy_whatsapp",
      "copy_e_mail",
      "contabilizacao_semanal",
      "canal_whatsapp",
      "campanhas_outbound",
      "campanha_de_baixo_toque",
      "base_retracao",
      "base_ht_publica",
      "base_de_contatos",
      "base_aa",
      "ativacao",
      "analise_de_bolsao",
      "alocacao_de_budget_de_campanha",
      "acao_1a1",
      "abastecimento_de_topo_de_funil",
      "abastecimento_de_funil",
      "aa"
    ],
    "itens_indexados": 185
  }
};
