window.WATCHDOG_INTEL = {
  "persona": {
    "nome": "Claudete",
    "papel": "Chief of Staff & Head of Marketing Analytics",
    "ultima_atualizacao": "2026-03-12T11:39:51.650703"
  },
  "ultima_atualizacao": "2026-03-13T08:55:08.015204",
  "arquitetura_memoria": {
    "modo": "camadas",
    "descricao": "Memoria viva enxuta + historico completo + resumos tematicos + indices.",
    "regras": {
      "memoria_viva": "Ultimos 24 aprendizados ativos e alertas abertos para uso frequente.",
      "historico": "Fonte permanente de know-how. Nunca deletar entradas do historico.",
      "resumos": "Primeira leitura para economizar token e acelerar contexto.",
      "indices": "Mapa rapido para abrir apenas o trecho historico necessario."
    }
  },
  "arquivos_relacionados": {
    "historico": "contexto/intel_historico.json",
    "resumos": "contexto/intel_resumos.json",
    "indices": "contexto/intel_indices.json"
  },
  "memoria_viva": {
    "insights_ativos_total_historico": 113,
    "insights_expostos_neste_arquivo": 24,
    "alertas_abertos_total_historico": 39,
    "alertas_expostos_neste_arquivo": 39,
    "temas_prioritarios": [
      "sdr",
      "base",
      "geral",
      "rr_sdr",
      "renovacao",
      "copy",
      "concorrencia",
      "campanha"
    ]
  },
  "resumos_tematicos": [
    {
      "tema": "sdr",
      "titulo": "SDR",
      "resumo_executivo": "Aprendizados-chave: HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de... | Copy de benefícios para Anos Anteriores performa melhor em escolas sem SDR atribuído — cold outreach WA é mais efetivo sem interferência de relacionamento prévio com SDR. Riscos abertos: LT PART em 7/30 convertidas (23%) e R$24.000/R$98.649 em receita (24%). O alerta041 registrou esse dado para a semana passada; o documento de hoje confirma que não houve recuper... | Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análi...",
      "aprendizados_ids": [
        "insight115",
        "insight104",
        "insight110",
        "insight081",
        "insight082",
        "insight083",
        "insight084",
        "insight085",
        "insight086",
        "insight089",
        "insight090",
        "insight091",
        "insight095",
        "insight096",
        "insight097",
        "insight078",
        "insight079",
        "insight080",
        "insight073",
        "insight071",
        "insight068",
        "insight069",
        "insight051",
        "insight053",
        "insight054",
        "insight061",
        "insight025",
        "insight027",
        "insight029",
        "insight031",
        "insight032",
        "insight033",
        "insight034",
        "insight035",
        "insight041",
        "insight002",
        "insight010",
        "insight012",
        "insight016",
        "insight018",
        "insight020",
        "insight021",
        "insight017"
      ],
      "alertas_ids": [
        "alerta045",
        "alerta046",
        "alerta039",
        "alerta040",
        "alerta042",
        "alerta036",
        "alerta037",
        "alerta032",
        "alerta030",
        "alerta025",
        "alerta026",
        "alerta024",
        "alerta020",
        "alerta012",
        "alerta014",
        "alerta001",
        "alerta004",
        "alerta005",
        "alerta006",
        "alerta009"
      ],
      "aprendizados_chave": [
        "HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de...",
        "Copy de benefícios para Anos Anteriores performa melhor em escolas sem SDR atribuído — cold outreach WA é mais efetivo sem interferência de relacionamento prévio com SDR.",
        "Concorrencia pode ter RR/SDR acima da meta mas zero alunos cadastrados na mesma semana. O desacoplamento indica que o gargalo esta na conversao RR->alunos, nao no volume de reun..."
      ],
      "riscos_abertos": [
        "LT PART em 7/30 convertidas (23%) e R$24.000/R$98.649 em receita (24%). O alerta041 registrou esse dado para a semana passada; o documento de hoje confirma que não houve recuper...",
        "Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análi..."
      ],
      "contagem_aprendizados": 44,
      "contagem_alertas_abertos": 20,
      "ultima_atualizacao": "2026-03-13"
    },
    {
      "tema": "base",
      "titulo": "Base",
      "resumo_executivo": "Aprendizados-chave: A base de WhatsApp da Estante Mágica usa apenas 2 dos 19 campos de telefone disponíveis no CRM. A oportunidade de expansão de alcance está no próprio banco de dados, não em enri... | No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc... Riscos abertos: LT PART em 7/30 convertidas (23%) e R$24.000/R$98.649 em receita (24%). O alerta041 registrou esse dado para a semana passada; o documento de hoje confirma que não houve recuper... | Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análi...",
      "aprendizados_ids": [
        "insight112",
        "insight114",
        "insight115",
        "insight102",
        "insight103",
        "insight106",
        "insight107",
        "insight110",
        "insight096",
        "insight097",
        "insight099",
        "insight100",
        "insight077",
        "insight078",
        "insight080",
        "insight073",
        "insight072",
        "insight070",
        "insight068",
        "insight065",
        "insight067",
        "insight047",
        "insight049",
        "insight044",
        "insight051",
        "insight058",
        "insight030",
        "insight032",
        "insight040",
        "insight041",
        "insight003",
        "insight004",
        "insight005",
        "insight007",
        "insight011",
        "insight018",
        "insight021"
      ],
      "alertas_ids": [
        "alerta045",
        "alerta046",
        "alerta048",
        "alerta041",
        "alerta037",
        "alerta031",
        "alerta032",
        "alerta033",
        "alerta026",
        "alerta020",
        "alerta021",
        "alerta017",
        "alerta005",
        "alerta007",
        "alerta011"
      ],
      "aprendizados_chave": [
        "A base de WhatsApp da Estante Mágica usa apenas 2 dos 19 campos de telefone disponíveis no CRM. A oportunidade de expansão de alcance está no próprio banco de dados, não em enri...",
        "No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc...",
        "Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-..."
      ],
      "riscos_abertos": [
        "LT PART em 7/30 convertidas (23%) e R$24.000/R$98.649 em receita (24%). O alerta041 registrou esse dado para a semana passada; o documento de hoje confirma que não houve recuper...",
        "Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análi..."
      ],
      "contagem_aprendizados": 37,
      "contagem_alertas_abertos": 15,
      "ultima_atualizacao": "2026-03-13"
    },
    {
      "tema": "geral",
      "titulo": "Geral",
      "resumo_executivo": "Riscos abertos: Nath levantou na daily que havia três tópicos enviados pela Claudete que não foram criados como tarefas. Pedro solicitou que informassem quais eram para ajustar. O documento não... | Pimentel sinalizou problema de contabilização de escolas convertidas ao final da daily — sem DRI ou prazo definidos. Distorce todas as métricas de meta.",
      "aprendizados_ids": [
        "insight116"
      ],
      "alertas_ids": [
        "alerta044",
        "alerta047",
        "alerta038",
        "alerta034",
        "alerta029",
        "alerta023",
        "alerta015",
        "alerta016",
        "alerta050"
      ],
      "aprendizados_chave": [],
      "riscos_abertos": [
        "Nath levantou na daily que havia três tópicos enviados pela Claudete que não foram criados como tarefas. Pedro solicitou que informassem quais eram para ajustar. O documento não...",
        "Pimentel sinalizou problema de contabilização de escolas convertidas ao final da daily — sem DRI ou prazo definidos. Distorce todas as métricas de meta."
      ],
      "contagem_aprendizados": 1,
      "contagem_alertas_abertos": 9,
      "ultima_atualizacao": "2026-03-13"
    },
    {
      "tema": "rr_sdr",
      "titulo": "RR/SDR",
      "resumo_executivo": "Aprendizados-chave: HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de... | Concorrencia pode ter RR/SDR acima da meta mas zero alunos cadastrados na mesma semana. O desacoplamento indica que o gargalo esta na conversao RR->alunos, nao no volume de reun... Riscos abertos: Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao... | Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes.",
      "aprendizados_ids": [
        "insight104",
        "insight095",
        "insight097",
        "insight054",
        "insight061",
        "insight031",
        "insight012",
        "insight021"
      ],
      "alertas_ids": [
        "alerta040",
        "alerta042",
        "alerta032",
        "alerta030",
        "alerta026",
        "alerta024",
        "alerta004",
        "alerta005"
      ],
      "aprendizados_chave": [
        "HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de...",
        "Concorrencia pode ter RR/SDR acima da meta mas zero alunos cadastrados na mesma semana. O desacoplamento indica que o gargalo esta na conversao RR->alunos, nao no volume de reun...",
        "SDRs em rampa de Novas (RR/SDR 0,11) tem produtividade 58% menor que rampados (0,21) e 58% abaixo da meta (0,26). Dado de marco confirma insight054 com benchmark quantificado."
      ],
      "riscos_abertos": [
        "Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao...",
        "Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes."
      ],
      "contagem_aprendizados": 8,
      "contagem_alertas_abertos": 8,
      "ultima_atualizacao": "2026-03-12"
    },
    {
      "tema": "renovacao",
      "titulo": "Renovacao",
      "resumo_executivo": "Aprendizados-chave: HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de... | Formato de vídeo personalizado estilo Spotify Wrapped (dados reais da escola) funciona como mecanismo de relacionamento antes de renovação — cria antecipação sem pressão de compra. Riscos abertos: Decisão na daily: disparo vídeos renovação Spotify na segunda 16/03. Base (descarte + perda sem conversão) deve estar validada até sexta 13/03 EOD. DRI não confirmado explicitam... | A semana de 03-06/mar encerrou com HT PART Renovação em 79% do RR/SDR semanal. Na daily 06/mar, as 22 RRs necessárias no último dia eram matematicamente impossíveis. O deficit d...",
      "aprendizados_ids": [
        "insight111",
        "insight114",
        "insight104",
        "insight109",
        "insight092",
        "insight093",
        "insight080",
        "insight073",
        "insight051",
        "insight026",
        "insight028",
        "insight031",
        "insight036",
        "insight038",
        "insight039",
        "insight002",
        "insight003",
        "insight004",
        "insight006",
        "insight007",
        "insight009",
        "insight018",
        "insight017",
        "insight023"
      ],
      "alertas_ids": [
        "alerta048",
        "alerta032",
        "alerta030",
        "alerta026",
        "alerta024",
        "alerta005",
        "alerta009"
      ],
      "aprendizados_chave": [
        "HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de...",
        "Formato de vídeo personalizado estilo Spotify Wrapped (dados reais da escola) funciona como mecanismo de relacionamento antes de renovação — cria antecipação sem pressão de compra.",
        "Tema 'Sem trabalho' em Renovação HT gera CPL 3-7x menor que Playlist para o mesmo público"
      ],
      "riscos_abertos": [
        "Decisão na daily: disparo vídeos renovação Spotify na segunda 16/03. Base (descarte + perda sem conversão) deve estar validada até sexta 13/03 EOD. DRI não confirmado explicitam...",
        "A semana de 03-06/mar encerrou com HT PART Renovação em 79% do RR/SDR semanal. Na daily 06/mar, as 22 RRs necessárias no último dia eram matematicamente impossíveis. O deficit d..."
      ],
      "contagem_aprendizados": 24,
      "contagem_alertas_abertos": 7,
      "ultima_atualizacao": "2026-03-13"
    },
    {
      "tema": "copy",
      "titulo": "Copy",
      "resumo_executivo": "Aprendizados-chave: No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc... | Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-... Riscos abertos: Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao... | Concorrencia abriu marco com 45% de fechadas/realizadas vs 58% em fevereiro - queda de 13pp sem causa documentada. Com 1 SDR a menos e bolsao herdado de fev, risco de degradacao...",
      "aprendizados_ids": [
        "insight115",
        "insight103",
        "insight106",
        "insight110",
        "insight093",
        "insight094",
        "insight099",
        "insight100",
        "insight075",
        "insight080",
        "insight070",
        "insight067",
        "insight061",
        "insight050",
        "insight042",
        "insight043",
        "insight052",
        "insight053",
        "insight057",
        "insight026",
        "insight003",
        "insight009",
        "insight018",
        "insight024"
      ],
      "alertas_ids": [
        "alerta040",
        "alerta025",
        "alerta018",
        "alerta012",
        "alerta013",
        "alerta007",
        "alerta011"
      ],
      "aprendizados_chave": [
        "No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc...",
        "Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-...",
        "Copy de benefícios para Anos Anteriores performa melhor em escolas sem SDR atribuído — cold outreach WA é mais efetivo sem interferência de relacionamento prévio com SDR."
      ],
      "riscos_abertos": [
        "Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao...",
        "Concorrencia abriu marco com 45% de fechadas/realizadas vs 58% em fevereiro - queda de 13pp sem causa documentada. Com 1 SDR a menos e bolsao herdado de fev, risco de degradacao..."
      ],
      "contagem_aprendizados": 24,
      "contagem_alertas_abertos": 7,
      "ultima_atualizacao": "2026-03-13"
    },
    {
      "tema": "concorrencia",
      "titulo": "Concorrencia",
      "resumo_executivo": "Aprendizados-chave: Campanhas de ativação de lista têm KPI primário diferente de levantada — alunos cadastrados e convertidas são o indicador correto, não CPL de levantada | O Cerco Mágico usa dois objetos físicos com funções distintas: (1) Revista Estante Mágica = mala direta tabloide para 4.716 escolas (AA+Ret+Conc), cria reconhecimento de marca;... Riscos abertos: Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes. | A daily decidiu ampliar a base de Concorrência segmentada (acima de 100 alunos) para as SDRs com melhor performance, em vez de mantê-la restrita a uma única SDR. Decisão tomada,...",
      "aprendizados_ids": [
        "insight086",
        "insight091",
        "insight093",
        "insight094",
        "insight095",
        "insight077",
        "insight078",
        "insight080",
        "insight071",
        "insight072",
        "insight070",
        "insight068",
        "insight067",
        "insight053",
        "insight061",
        "insight050",
        "insight042",
        "insight044",
        "insight052",
        "insight025",
        "insight027",
        "insight028",
        "insight029",
        "insight031",
        "insight032",
        "insight035",
        "insight036",
        "insight037",
        "insight002",
        "insight006",
        "insight011",
        "insight021",
        "insight017"
      ],
      "alertas_ids": [
        "alerta042",
        "alerta037",
        "alerta025",
        "alerta021"
      ],
      "aprendizados_chave": [
        "Campanhas de ativação de lista têm KPI primário diferente de levantada — alunos cadastrados e convertidas são o indicador correto, não CPL de levantada",
        "O Cerco Mágico usa dois objetos físicos com funções distintas: (1) Revista Estante Mágica = mala direta tabloide para 4.716 escolas (AA+Ret+Conc), cria reconhecimento de marca;...",
        "Concorrencia pode ter RR/SDR acima da meta mas zero alunos cadastrados na mesma semana. O desacoplamento indica que o gargalo esta na conversao RR->alunos, nao no volume de reun..."
      ],
      "riscos_abertos": [
        "Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes.",
        "A daily decidiu ampliar a base de Concorrência segmentada (acima de 100 alunos) para as SDRs com melhor performance, em vez de mantê-la restrita a uma única SDR. Decisão tomada,..."
      ],
      "contagem_aprendizados": 33,
      "contagem_alertas_abertos": 4,
      "ultima_atualizacao": "2026-03-11"
    },
    {
      "tema": "campanha",
      "titulo": "Campanhas",
      "resumo_executivo": "Aprendizados-chave: Priorização de escolas High Value no Outbound pode reduzir volume de levantadas porque histórico mostra que escolas de médio e micro porte são as que mais convertem nesse canal.... | No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc... Riscos abertos: Numero utilizado no teste de ligacoes WA com 30 escolas sofreu bloqueio na Meta, possivelmente por denuncia. Nao esta claro se e o numero principal ou temporario. Se for o princ... | Pedro propôs envio de WA utilitário antes de cada ligação SDR. Ana Paula levantou risco de saturação. Lili não concluiu a deliberação. A daily encerrou sem decisão formal, sem D...",
      "aprendizados_ids": [
        "insight101",
        "insight103",
        "insight106",
        "insight108",
        "insight109",
        "insight110",
        "insight093",
        "insight094",
        "insight100",
        "insight074",
        "insight075",
        "insight076",
        "insight080",
        "insight071",
        "insight030",
        "insight040",
        "insight041",
        "insight003",
        "insight005",
        "insight009",
        "insight015",
        "insight018"
      ],
      "alertas_ids": [
        "alerta039",
        "alerta036",
        "alerta017",
        "alerta007"
      ],
      "aprendizados_chave": [
        "Priorização de escolas High Value no Outbound pode reduzir volume de levantadas porque histórico mostra que escolas de médio e micro porte são as que mais convertem nesse canal....",
        "No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciproc...",
        "Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-..."
      ],
      "riscos_abertos": [
        "Numero utilizado no teste de ligacoes WA com 30 escolas sofreu bloqueio na Meta, possivelmente por denuncia. Nao esta claro se e o numero principal ou temporario. Se for o princ...",
        "Pedro propôs envio de WA utilitário antes de cada ligação SDR. Ana Paula levantou risco de saturação. Lili não concluiu a deliberação. A daily encerrou sem decisão formal, sem D..."
      ],
      "contagem_aprendizados": 22,
      "contagem_alertas_abertos": 4,
      "ultima_atualizacao": "2026-03-12"
    }
  ],
  "aprendizados": [
    {
      "id": "insight111",
      "titulo": "Caneca e Sem trabalho sao as melhores ofertas para Renovacao HT como levantada — CPL < R$12 confirmado em Feb e Mar/2026",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Caneca Feb/23: CPL R$6.60 (54 lev). Caneca Feb/25: CPL R$11.38 (29 lev). Sem trabalho Publica Mar/09: CPL R$8.94 (9 lev). Sem trabalho Particular Mar/10: CPL R$10.22 (41 lev). Playlist Renovacao Mar/03: objetivo era conversao (cadastro de alunos), nao levantada — gerou 3+3+2 convertidas, avaliacao de eficacia como conversao pendente. Nao comparar Playlist com Caneca/Sem trabalho para objetivo de levantada.",
      "acao_sugerida": "Priorizar Caneca e Sem trabalho em disparos de Renovacao HT com objetivo de levantada. Playlist tem objetivo distinto (conversao de alunos) e nao deve ser comparado diretamente. Avaliar CPL de Playlist como custo por cadastro de alunos, nao por levantada.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026",
      "ultima_atualizacao": "2026-03-13T08:53:35.944357"
    },
    {
      "id": "insight112",
      "titulo": "Anos Anteriores tem CPL estruturalmente baixo (R$3-6) independente da oferta — segmento mais eficiente do portfolio",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Jan/12 Presente exclusivo: CPL ~R$3.02 (68 lev/623 base). Jan/27 Visibilidade: CPL ~R$5.76 (30 lev). Feb/03 Playlist: CPL ~R$4.60 (94 lev/1205 base). Feb/25 Caneca: CPL ~R$4.53 (114 lev/1413 base). Mar/11 Beneficios especiais: CPL ~R$22.74 (18 lev, base menor).",
      "acao_sugerida": "Priorizar AA em semanas de orcamento restrito. Qualquer oferta funciona neste segmento. Escalar base quando disponivel.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026"
    },
    {
      "id": "insight113",
      "titulo": "Retracao A/B Mar/2026: Presente exclusivo supera Sem trabalho (2.65% vs 1.47%, CPL R$20 vs R$37)",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Teste A/B 11/03/2026 — Presente exclusivo: 7 lev de 549 base (2.65%), CPL R$20.37. Sem trabalho: 4 lev de 520 base (1.47%), CPL R$36.86. Volume absoluto baixo — Retracao tem engajamento estruturalmente menor que outros baldinhos.",
      "acao_sugerida": "Usar Presente exclusivo como oferta padrao para Retracao. Nao repetir Sem trabalho neste segmento sem nova hipotese clara. Volume permanece baixo — Retracao precisa de abordagem complementar alem de disparo WA.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026"
    },
    {
      "id": "insight114",
      "titulo": "Renovacao Publica HT tem CPL historico abaixo de R$9 — segmento estruturalmente eficiente mesmo com base pequena",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Feb/09 (>5k Publica): CPL R$7.02, 55 lev de 443 base (12.4%). Mar/09 (HT Publica Sem trabalho): CPL R$8.94, 9 lev de 210 base (4.3%). Consistente em dois meses com ofertas diferentes.",
      "acao_sugerida": "Manter Renovacao Publica HT na programacao mensal. Priorizar em janelas de orcamento reduzido. Base pequena mas qualidade alta.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026"
    },
    {
      "id": "insight115",
      "titulo": "Outbound SDR via WA tem CPL nao-sustentavel em bases grandes (>500) — padrao confirmado Jan, Feb e Mar/2026",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Jan/29 (1186 base): 9 lev, CPL R$34.92. Feb/23 (3118 base, Playlist): 2 lev, CPL R$361.26. Mar/12 (2625 base HV — High Value — ja segmentada, menor parcela): 5 lev, CPL R$121.72. Confirmado: base Mar/12 era exclusivamente HV, ja qualificada. O problema nao e segmentacao de qualidade — e que WA Outbound nao funciona nem para HV em volume. Padrao: qualquer base Outbound > 500 produziu CPL acima de R$30.",
      "acao_sugerida": "Suspender disparos Outbound SDR em bases > 500. Mesmo com base HV qualificada, resultado e insatisfatorio. Testar micro-lotes (<200 contatos HV) com copy especifico para perfil HV antes de escalar. Investigar se o canal WA e adequado para HV ou se o perfil HV responde melhor a outro canal (email, SDR direto). Ver alerta046 e alerta011.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026",
      "fonte": "planilha_disparos_vit_jan_mar_2026",
      "ultima_atualizacao": "2026-03-13T08:53:35.944357"
    },
    {
      "id": "insight116",
      "titulo": "Canal herois (CS form) e o maior gerador de levantadas de MKT — sem custo de midia, via time de Suporte ao Cliente",
      "tema": "campanha",
      "data": "2026-03-13",
      "status": "ativo",
      "evidencia": "Fevereiro: 208 de 257 levantadas totais (81%) via herois. Marco ate 12/03: 103 levantadas via herois vs 89 via disparos WA. Herois = time de CS que recebe emails e WA organicos de escolas, preenche forms e encaminha ticket. Processo hoje 95% operado pelo time de Marketing. Sem custo de midia associado. Tambem ha levantadas via Instagram e via email, alem de herois — tres canais nao-disparo WA.",
      "acao_sugerida": "Considerar herois + Instagram + email como 'levantadas nao-disparo' no relatorio mensal para separar o custo real de cada canal. Avaliar o volume de herois como proxy de demanda organica inbound — se cresce, e sinal de brand awareness ativo. Nao confundir com levantada gerada por disparo WA — sao canais independentes.",
      "contexto": "Resposta da Vit ao debriefing da planilha de disparos Mar/2026",
      "fonte": "feedback_vit_13_03_2026"
    },
    {
      "id": "insight101",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "gatilho": "queda levantadas Outbound 5 para 3,75",
      "insight": "Priorização de escolas High Value no Outbound pode reduzir volume de levantadas porque histórico mostra que escolas de médio e micro porte são as que mais convertem nesse canal. Alta segmentação por valor unitário inverte a lógica de volume que sustenta o funil Outbound.",
      "evidencia": "Vitória reportou queda de média de levantadas de 5 para 3,75 por disparo vs ano anterior. Lili e Vit levantaram hipótese de que a segmentação atual (High Value) pode ser a causa, dado que médio/micro historicamente convertiam mais nesse canal.",
      "confianca": "media",
      "aplicavel_a": [
        "Outbound",
        "segmentação de base"
      ],
      "acao_sugerida": "Antes de ajustar segmentação Outbound, sempre comparar CPL e taxa de levantada por tier de escola (High Value vs médio vs micro) no histórico. Não assumir que High Value = melhor canal Outbound — o canal pode ter perfil de público diferente do canal de relacionamento.",
      "status": "ativo"
    },
    {
      "id": "insight102",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "operacao",
      "gatilho": "base WhatsApp 19 campos vs 2 utilizados",
      "insight": "A base de WhatsApp da Estante Mágica usa apenas 2 dos 19 campos de telefone disponíveis no CRM. A oportunidade de expansão de alcance está no próprio banco de dados, não em enriquecimento externo. Testar o envio utilitário para os campos não abordados e remover quem não responde é a forma mais rápida e barata de limpar e expandir a base simultaneamente.",
      "evidencia": "Vit identificou 19 campos de telefone; apenas 2 estão sendo usados nos disparos. Lili priorizou ampliar o raio antes de validar, com plano de teste via envio utilitário seguido de remoção dos não-respondentes.",
      "confianca": "alta",
      "aplicavel_a": [
        "WhatsApp",
        "base de contatos",
        "campanhas outbound"
      ],
      "acao_sugerida": "Sempre verificar cobertura de campos de telefone no CRM antes de contratar enriquecimento externo. Expansão interna de campos é mais rápida, mais barata e valida a base como efeito colateral do próprio disparo.",
      "status": "ativo"
    },
    {
      "id": "insight103",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "gatilho": "teste A/B retração presente exclusivo vs sem trabalho",
      "insight": "No segmento de Retração, copy com argumento emocional/reciprocidade ('presente exclusivo') tem CPL R$28 contra R$73 do argumento funcional ('sem trabalho'). O ângulo de reciprocidade supera o de facilidade operacional em 2,6x nesse público — que já conhece o produto e provavelmente tem objeção emocional, não operacional.",
      "evidencia": "Vit apresentou resultado do teste A/B de retração: 'presente exclusivo' CPL R$28, 'sem trabalho' CPL R$73. Resultado do dia 12/mar.",
      "confianca": "alta",
      "aplicavel_a": [
        "Retração",
        "copy WhatsApp",
        "copy e-mail"
      ],
      "acao_sugerida": "Para base de Retração, sempre usar ângulo de reciprocidade/presente como copy principal. Argumento funcional ('não dá trabalho') deve ser tratado como contorno de objeção secundária, não como gancho de abertura.",
      "status": "ativo"
    },
    {
      "id": "insight104",
      "data": "2026-03-12",
      "fonte": "Nath 12.03.26 Meta Aquisição 26 _ Daily comercial _ Ações da semana.pdf",
      "categoria": "funil",
      "insight": "HT PÚB tem a maior taxa de fechamento da cartela (235% da meta semanal) mas volume de Realizadas em 58% — o gargalo não é conversão, é abastecimento de topo de funil. Produto de maior eficiência sendo sub-abastecido.",
      "evidencia": "HT PÚB Semanal: Tx Fechadas 235% da meta, Realizadas 4/11 (58% YTD), RR/SDR 1,33/2,29 (58%).",
      "confianca": "alta",
      "aplicavel_a": [
        "HT_PUB",
        "Renovacao"
      ],
      "acao_sugerida": "Em HT PÚB, alavanca de resultado é volume de prospecção (RR/SDR), não melhoria de discurso. Priorizar abastecimento de topo quando meta mensal estiver em risco.",
      "status": "ativo"
    },
    {
      "id": "insight106",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Copy 'presente exclusivo' supera 'sem trabalho' em Retração com margem expressiva: CPL R$28 vs R$73 (2,6x mais barato). Consistente com benchmark anterior (insight100: CPL R$15-29).",
      "evidencia": "Teste A/B Retração 12/03: 'presente exclusivo' CPL R$28, 'sem trabalho' CPL R$73 — apresentado por Vitória na daily.",
      "confianca": "alta",
      "aplicavel_a": [
        "Retracao"
      ],
      "acao_sugerida": "Adotar 'presente exclusivo' como copy padrão em toda comunicação de Retração; descontinuar variantes baseadas em ausência de esforço.",
      "status": "ativo"
    },
    {
      "id": "insight108",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Segmentação exclusiva em High Value pode estar deprimindo taxa de levantadas no Outbound: queda de 5 para 3,75 levantadas/disparo vs ano anterior (-25%), pois escolas médio e micro porte historicamente convertiam mais.",
      "evidencia": "Vitória apresentou queda de desempenho Outbound; hipótese levantada por Liliane e Vitória na daily 12/03.",
      "confianca": "media",
      "aplicavel_a": [
        "Outbound"
      ],
      "acao_sugerida": "Incluir segmento médio e micro porte em testes de Outbound ao lado do High Value para isolar se a queda é de segmentação ou de mercado.",
      "status": "ativo"
    },
    {
      "id": "insight109",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Formato de vídeo personalizado estilo Spotify Wrapped (dados reais da escola) funciona como mecanismo de relacionamento antes de renovação — cria antecipação sem pressão de compra.",
      "evidencia": "Liliane relatou sucesso histórico do formato; daily decidiu expandir para escolas em descarte/perda com disparo 16/03.",
      "confianca": "media",
      "aplicavel_a": [
        "Renovacao",
        "Anos Anteriores"
      ],
      "acao_sugerida": "Após validar resultado de 16/03, criar playbook do formato Spotify Wrapped para reuso em reativação e renovação.",
      "status": "ativo"
    },
    {
      "id": "insight110",
      "data": "2026-03-12",
      "fonte": "Daily _ Gestão Comercial - 2026_03_12 10_31 GMT-03_00 - Anotações do Gemini.pdf",
      "categoria": "campanha",
      "insight": "Copy de benefícios para Anos Anteriores performa melhor em escolas sem SDR atribuído — cold outreach WA é mais efetivo sem interferência de relacionamento prévio com SDR.",
      "evidencia": "Pedro Concy e Pimentel observaram na análise de disparos que copy benefícios funcionou especialmente bem em escolas sem SDR atribuído.",
      "confianca": "media",
      "aplicavel_a": [
        "Anos Anteriores"
      ],
      "acao_sugerida": "Segmentar base Anos Anteriores por presença/ausência de SDR atribuído e calibrar copy: benefícios para sem SDR, relacionamento para com SDR.",
      "status": "ativo"
    },
    {
      "id": "insight081",
      "data": "2026-03-11",
      "fonte": "Escuta de audio SDR 10/mar/26",
      "titulo": "SDR que cede a objecao de email sem reforcar valor da reuniao perde o agendamento",
      "descricao": "Padrao: SDR faz bom contorno inicial mas cede no final concordando em enviar pre-apresentacao sem reforcar que proposta personalizada e condicoes exclusivas so sao possiveis na reuniao. Ao ceder ao email deve: (1) desvalorizar conteudo do email (apresentacao superficial/generalizada), (2) reforcar que proposta real so na reuniao.",
      "categoria": "sdr",
      "status": "ativo",
      "evidencia": "Chamada de Mariana Nogueira analisada na sessao de escuta 10/mar/26. Leticia Montemor identificou o padrao como ponto negativo recorrente.",
      "acao_sugerida": "Incluir no discurso padrao: ao ceder ao email, desvalorizar o conteudo (generica, superficial) e reforcar que proposta personalizada e condicoes exclusivas so na reuniao com especialista."
    },
    {
      "id": "insight082",
      "data": "2026-03-11",
      "fonte": "Escuta de audio SDR 10/mar/26",
      "titulo": "Beneficio (financeiro ou playlist) deve ser guardado para o MEIO da ligacao, nao revelado no inicio",
      "descricao": "Revelar o beneficio logo no inicio gera animacao superficial sem engajamento na proposta consultiva. Guardar para o meio mantem a gestora engajada ate a proposta e permite adaptar o beneficio ao contexto da escola.",
      "categoria": "sdr",
      "status": "ativo",
      "evidencia": "Sara Penteado e Bebel Bertuccelli na sessao de escuta 10/mar/26. Bebel observou que a mencao inicial ao beneficio foi feita sem conviccao e sem vender a exclusividade.",
      "acao_sugerida": "No discurso padrao SDR: mencionar a existencia de um beneficio exclusivo no inicio (para gerar interesse), guardar detalhes (financeiro ou playlist) para o meio. Incluir no checklist visual Wydi."
    },
    {
      "id": "insight083",
      "data": "2026-03-11",
      "fonte": "Escuta de audio SDR 10/mar/26",
      "titulo": "Pesquisar historico do card antes de ligar e usar objecoes e dores passadas como gancho",
      "descricao": "Escolas com contato anterior tem historico de objecoes e dores no CRM. SDR que pesquisa antes da ligacao pode usar como gancho e prevenir negativa imediata. Especialmente valido para escolas novas que ja tiveram contato mas nao aplicaram.",
      "categoria": "sdr",
      "status": "ativo",
      "evidencia": "Sara Penteado e Wydi Gomes na sessao de escuta 10/mar/26. Escola Novas tinha gestora que tentou aplicar no ano anterior mas foi barrada pela central - informacao disponivel no card mas nao usada pelo SDR.",
      "acao_sugerida": "Regra obrigatoria pre-ligacao: abrir o card no CRM e verificar historico de trocas e objecoes. Usar como gancho na abordagem. Incluir no checklist visual SDR como primeiro passo."
    },
    {
      "id": "insight084",
      "data": "2026-03-11",
      "fonte": "Escuta de audio SDR 10/mar/26",
      "titulo": "Perguntar sobre projetos ou atividades internas voltadas para leitura e escrita - nao apenas projetos",
      "descricao": "Quando SDR pergunta apenas sobre projetos, gestora ou secretaria tende a negar (o que e improvavel). A formulacao mais precisa - atividades internas voltadas para leitura e escrita - reduz a negativa reflexa e aumenta a precisao da informacao coletada.",
      "categoria": "sdr",
      "status": "ativo",
      "evidencia": "Wydi Gomes observou durante analise da chamada de Mari na sessao de escuta 10/mar/26. Gestora negou ter projetos quando perguntada de forma generica.",
      "acao_sugerida": "Substituir pergunta generica por: projetos ou atividades internas voltadas para leitura e escrita. Atualizar no script padrao SDR (t152)."
    },
    {
      "id": "insight085",
      "data": "2026-03-11",
      "fonte": "Encontro Aquisicao 04/mar/26 (Lili)",
      "titulo": "Maior gargalo do funil SDR por volume e a barreira da secretaria - 30% das ligacoes nao chegam a gestora",
      "descricao": "30% das ligacoes SDR sao barradas na secretaria que nao passa para a coordenadora/gestora. E o maior ponto de perda por volume no funil. Papel do Mkt no Cerco Magico e cercar a escola antes da ligacao SDR para que a gestora ja conheca a EM e a secretaria passe.",
      "categoria": "funil",
      "status": "ativo",
      "evidencia": "Encontro Aquisicao 04/mar/26 coordenado por Lili. Item 2 do documento de oportunidades por etapa de funil.",
      "acao_sugerida": "Fortalecer o Cerco Magico como solucao estrutural para a barreira da secretaria. Medir % de ligacoes barradas na secretaria vs que chegam a gestora por baldinho para rastrear impacto do cerco."
    },
    {
      "id": "insight086",
      "data": "2026-03-11",
      "fonte": "Escuta de audio SDR 10/mar/26",
      "titulo": "Escola que usou concorrencia pode retornar com carinho e receptividade pela EM - encantamento e ativo estrategico em AA",
      "descricao": "Escola do segmento AA que optou por concorrentes no ano anterior demonstrou alta receptividade e carinho pela EM quando abordada. O encantamento historico da EM com a escola e um ativo estrategico em AA que deve ser explorado na abordagem.",
      "categoria": "canal",
      "status": "ativo",
      "evidencia": "Chamada de Tati para escola de Anos Anteriores na sessao de escuta 10/mar/26. Gestora Mirla demonstrou saudades da EM e curiosidade sobre novidades mesmo tendo usado Lives e Ciranda de Livros no ano anterior.",
      "acao_sugerida": "No segmento AA: usar historico de relacionamento com a EM como gancho primario. Escola que foi para concorrencia nao e lead frio - e lead quente com historia. Perguntar sobre a experiencia anterior e validar o carinho existente."
    },
    {
      "id": "insight087",
      "data": "2026-03-11",
      "fonte": "Encontro Aquisicao 04/mar/26 (Lili)",
      "titulo": "Queda de levantadas 2024 para 2025 pode estar correlacionada com mudanca de argumento principal (MEL para antecipacao de receita)",
      "descricao": "Em 2024 argumento central era MEL (motivacao emocional do livro); em 2025 mudou para objetivo de antecipacao de receita. Houve queda de levantadas. Hipotese: MEL tinha maior ressonancia emocional com gestoras do que o argumento de receita. Ainda e hipotese - requer investigacao de Mkt.",
      "categoria": "oferta",
      "status": "ativo",
      "evidencia": "Encontro Aquisicao 04/mar/26 (Lili) - item 4. Queda de levantadas de 24 para 25 identificada. Hipotese levantada por Lili.",
      "acao_sugerida": "Karina investigar argumento MEL de 2024: quais materiais, qual formulacao, qual resultado. Avaliar se e replicavel ou adaptavel para 2026. Task t148 criada para esse fim."
    },
    {
      "id": "insight088",
      "data": "2026-03-11",
      "fonte": "Encontro Aquisicao 04/mar/26 (Lili)",
      "titulo": "Disparo WA so ocorre para campo celular - outros campos de contato nao sao alcancados, representando perda de alcance",
      "descricao": "Disparo de WA utilitario so acontece para registros com campo celular preenchido. Outros campos de contato nao recebem disparos, representando escolas potencialmente alcancaveis que nao estao sendo contatadas. Custo do utilitario: R$0,09 por disparo.",
      "categoria": "canal",
      "status": "ativo",
      "evidencia": "Encontro Aquisicao 04/mar/26 (Lili) - item 1.1. Validacao de WPP identificada como oportunidade com impacto em conversao.",
      "acao_sugerida": "Vitoria implementar disparo WA utilitario para campos alem de celular (t143). Medir impacto em taxa de atendimento apos implementacao."
    },
    {
      "id": "insight089",
      "data": "2026-03-11",
      "fonte": "Mensagem da Lua.pdf",
      "titulo": "Ligacao via WhatsApp em prospeccao B2B escola gera bloqueio de numero e percepcao de invasao — canal inviavel como padrao",
      "descricao": "Teste com 30 escolas (ligacoes via WA) resultou em 1 reuniao (3,3% de conversao) e bloqueio do numero institucional pela Meta, possivelmente por denuncia de escola. 2 escolas declararam explicitamente que nao atendem ligacoes via WhatsApp. Percepcao das gestoras e de invasao, nao de contato comercial legitimo. Compromete o numero como ativo estrategico.",
      "categoria": "canal",
      "status": "ativo",
      "evidencia": "30 escolas trabalhadas, 5 contatos efetivos, 1 reuniao realizada, numero bloqueado na Meta. 2 escolas recusaram explicitamente ligacoes WA.",
      "acao_sugerida": "Nunca usar ligacao via WhatsApp como canal padrao de prospeccao SDR. Reservar WA para ultimo recurso (todos canais tentados, escola seria descartada). Usar numero descartavel dedicado se necessario."
    },
    {
      "id": "insight090",
      "data": "2026-03-11",
      "fonte": "Mensagem da Lua.pdf",
      "titulo": "Blip com autorizacao previa transforma ligacao fria em canal autorizado — reduz risco operacional mas exige etapa adicional",
      "descricao": "Estrategia de Lua: (1) WA como canal de suporte, (2) mensagem solicitando autorizacao para contato por voz, (3) apos autorizacao, ligacao via Blip. Muda percepcao da gestora de ligacao invasiva para canal autorizado. Dependente da resolucao do alerta020 (risco de bloqueio permanente do Blip).",
      "categoria": "sdr",
      "status": "ativo",
      "evidencia": "Recomendacao estrategica de Lua apos teste de 30 escolas. Alinha com alerta020.",
      "acao_sugerida": "Quando alerta020 for resolvido, adotar protocolo de 3 etapas de Lua como padrao para ligacoes SDR: WA suporte -> autorizacao -> ligacao Blip. Nunca implementar antes de resolver risco de bloqueio permanente."
    }
  ],
  "criticas_ativas": [
    {
      "id": "alerta044",
      "data": "2026-03-12",
      "titulo": "Três tópicos da Claudete sem tarefa criada — risco de ação perdida",
      "critica": "Nath levantou na daily que havia três tópicos enviados pela Claudete que não foram criados como tarefas. Pedro solicitou que informassem quais eram para ajustar. O documento não identifica quais são esses três tópicos, e não há DRI nem prazo definido para resolver o gap.",
      "acao_sugerida": "Claudete deve listar os 3 tópicos não-tarefizados e enviar para Pedro até 13/mar para criação formal.",
      "prioridade": "media",
      "dri": "Claudete",
      "status": "aberto",
      "nota_status": "Mencionado na daily 12/mar. Contexto: Nath levantou a dúvida, Pedro pediu a lista. Nenhuma resolução registrada no documento."
    },
    {
      "id": "alerta045",
      "data": "2026-03-12",
      "titulo": "LT PART: 23% de convertidas e 24% de receita com 12 dias úteis restantes",
      "critica": "LT PART em 7/30 convertidas (23%) e R$24.000/R$98.649 em receita (24%). O alerta041 registrou esse dado para a semana passada; o documento de hoje confirma que não houve recuperação — os números são praticamente iguais. Com ~12 dias úteis restantes em março (supondo ~15 dias úteis no mês e 3 já executados), fechar os 23 convertidas restantes exigiria quase 2 convertidas por dia útil. A base cadastrada de 272 alunos e custo de disparo R$378 sugerem que a ação de disparo está ocorrendo, mas a conversão não está acompanhando. Isso é diferente do alerta041 (que focava em ausência de disparo) — aqui o disparo ocorreu e a conversão está baixa.",
      "acao_sugerida": "Kaká ou Vit: verificar se houve follow-up comercial nas 272 escolas com alunos cadastrados via LT PART que ainda não converteram — se o disparo gerou cadastro mas não gerou contato SDR, o funil está vazando entre marketing e comercial.",
      "prioridade": "alta",
      "dri": "Karina Machado",
      "status": "aberto",
      "nota_status": "2026-03-12: LT PART 7/30 convertidas (23%), R$24k/R$98k (24%). 272 alunos cadastrados indicam que o disparo gerou interesse, mas conversão não acompanhou. Alerta041 era sobre ausência de disparo; este é sobre gargalo de conversão pós-cadastro."
    },
    {
      "id": "alerta046",
      "data": "2026-03-12",
      "titulo": "Queda de performance Outbound sem diagnóstico formal",
      "critica": "Média de levantadas Outbound caiu de 5 para 3,75 por disparo vs ano anterior (-25%). Hipótese: segmentação High Value exclui segmentos historicamente mais responsivos. Sem análise formal nem plano de ação.",
      "acao_sugerida": "Vitória analisar composição da base Outbound 2025 vs 2026 (porte, SDR atribuído, segmento) e apresentar hipótese validada até 13/03.",
      "prioridade": "alta",
      "dri": "Vitória",
      "status": "aberto",
      "nota_status": "",
      "evidencia": "Mar/12 confirmado: 2.625 base, 5 lev (0.19%), CPL R$121,72 — pior CPL do historico de disparos Outbound. Padrao consolidado em 3 meses consecutivos. Ver insight115.",
      "ultima_atualizacao": "2026-03-13T08:51:54.377989"
    },
    {
      "id": "alerta047",
      "data": "2026-03-12",
      "titulo": "Inconsistência na contabilização de escolas convertidas",
      "critica": "Pimentel sinalizou problema de contabilização de escolas convertidas ao final da daily — sem DRI ou prazo definidos. Distorce todas as métricas de meta.",
      "acao_sugerida": "Pimentel mapear qual sistema/campo gera inconsistência na contagem de convertidas e acionar tecnologia se necessário até 16/03.",
      "prioridade": "alta",
      "dri": "Pimentel",
      "status": "aberto",
      "nota_status": ""
    },
    {
      "id": "alerta048",
      "data": "2026-03-12",
      "titulo": "Base renovação precisa estar pronta hoje para disparo de segunda",
      "critica": "Decisão na daily: disparo vídeos renovação Spotify na segunda 16/03. Base (descarte + perda sem conversão) deve estar validada até sexta 13/03 EOD. DRI não confirmado explicitamente.",
      "acao_sugerida": "Vitória confirmar base de renovação pronta e validada até sexta 13/03 EOD.",
      "prioridade": "critica",
      "dri": "Vitória",
      "status": "aberto",
      "nota_status": ""
    },
    {
      "id": "alerta039",
      "data": "2026-03-11",
      "titulo": "Numero WA institucional bloqueado pela Meta durante teste SDR — ativo de contato comprometido",
      "critica": "Numero utilizado no teste de ligacoes WA com 30 escolas sofreu bloqueio na Meta, possivelmente por denuncia. Nao esta claro se e o numero principal ou temporario. Se for o principal, todos os disparos, campanhas e contatos ativos estao em risco.",
      "acao_sugerida": "Luana confirmar hoje se o numero bloqueado e o principal ou temporario. Se for o principal: Pedro e Vitoria acionam recuperacao junto a Meta imediatamente. Documentar numero afetado e isolar das campanhas ate recuperacao confirmada.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberto",
      "nota_status": "Identificado via Mensagem da Lua.pdf em 11/mar/2026"
    },
    {
      "id": "alerta040",
      "data": "2026-03-11",
      "titulo": "Retracao semanal em colapso (2/14 RRs, 29% RR/SDR) e Outbound abaixo (6/20)",
      "critica": "Pior ritmo semanal registrado em Retracao. Outbound tambem abaixo da meta semanal. A/B email disparado hoje; WA amanha 8h com copy vencedor. Se ate quinta nao houver recuperacao, risco de marco fechar abaixo.",
      "acao_sugerida": "Vitoria executar WA amanha 8h com copy vencedor do A/B. Se ate quinta 14/03 sem recuperacao significativa, Pimentel acionar reforco de SDR ou redirecionamento de capacidade.",
      "prioridade": "critica",
      "dri": "Vitoria Riente",
      "status": "aberto",
      "nota_status": "A/B email disparado 11/03. WA previsto amanha 8h."
    },
    {
      "id": "alerta041",
      "data": "2026-03-11",
      "titulo": "Novas semanal com zero alunos cadastrados (0/845) e LT PART em 24% da meta mensal",
      "critica": "Meta alunos semanal Novas: 0/845 (0%). LT PART: 7/30 convertidas (23%), R$24k/R$98k. Sem acao de disparo esta semana, ambas fecham o mes abaixo.",
      "acao_sugerida": "Autorizar disparo WA para base Novas em etapas iniciais (entrada, tentativa) ate 13/mar, filtrando acima de 80 alunos. Vitoria executa, Nath valida base antes. Karina entregar plano LT PART hoje (t161).",
      "prioridade": "alta",
      "dri": "Vitoria Riente",
      "status": "aberto",
      "nota_status": "Aguardando Nath validar base elegivel"
    },
    {
      "id": "alerta042",
      "data": "2026-03-11",
      "titulo": "Concorrencia paradoxo: RR/SDR 102% mas zero alunos cadastrados na semana",
      "critica": "Concorrencia: RR/SDR 102% mas 0% de meta de alunos na semana (0/721). Meta mensal em 27% (216/2.963). Paradoxo indica gargalo na conversao RR->alunos, nao no volume de reunioes.",
      "acao_sugerida": "Nath investigar causa do gap RR/SDR vs alunos em Concorrencia na semana 11/03. Diagnostico ate sexta-feira 13/03.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberto",
      "nota_status": "Tarefa de investigacao criada (t161)"
    },
    {
      "id": "alerta036",
      "data": "2026-03-10",
      "titulo": "Decisão de WA utilitário pré-ligação sem DRI e sem protocolo de teste",
      "critica": "Pedro propôs envio de WA utilitário antes de cada ligação SDR. Ana Paula levantou risco de saturação. Lili não concluiu a deliberação. A daily encerrou sem decisão formal, sem DRI e sem definição de teste controlado. Se alguém implementar sem protocolo, pode comprometer o canal WA que já está em uso pela campanha LT e pelo Cerco Mágico.",
      "acao_sugerida": "Pedro ou Lili definir até 12/mar: (1) se o WA utilitário será testado ou arquivado, (2) se testado — DRI, frequência máxima por contato, tamanho da amostra e KPI de sucesso/fracasso.",
      "prioridade": "alta",
      "dri": "Pedro Concy",
      "status": "aberto",
      "nota_status": "DRI atualizado para Pedro em 11/mar/2026. Pedro assume decisao: (1) testar ou arquivar WA utilitario pre-ligacao SDR, (2) se testar: definir DRI execucao, frequencia, amostra e KPI."
    },
    {
      "id": "alerta037",
      "data": "2026-03-10",
      "titulo": "Base de Concorrência segmentada (+100 alunos) restrita a uma SDR — expansão deliberada mas sem DRI",
      "critica": "A daily decidiu ampliar a base de Concorrência segmentada (acima de 100 alunos) para as SDRs com melhor performance, em vez de mantê-la restrita a uma única SDR. Decisão tomada, mas não há DRI nomeado para executar a redistribuição nem prazo definido. Sem execução, a decisão não tem efeito na média de alunos de março.",
      "acao_sugerida": "Ana Paula Pimentel executar redistribuição da base +100 alunos de Concorrência entre as 2-3 melhores SDRs até 12/mar, validando performance prévia com Nath antes da redistribuição.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberto",
      "nota_status": "Decisão tomada na daily de 10/mar/2026 sem tarefa gerada"
    },
    {
      "id": "alerta038",
      "data": "2026-03-10",
      "titulo": "Custo da Revista e mala direta desagregado — realizado não atualizado no orçamento",
      "critica": "Vit informou custo total de R$11.500 (revista + carta de dezembro) mas Lili pediu separação entre custo de produção e custo de envio da revista especificamente, além de atualização do realizado no controle de orçamento. Sem essa separação, o orçamento de marketing do Cerco Mágico (que inclui nova revista) não tem referência de custo unitário confiável.",
      "acao_sugerida": "Vitória separar custo de produção e envio da revista de dezembro e atualizar o realizado no controle de orçamento de marketing até 12/mar.",
      "prioridade": "media",
      "dri": "Vitória",
      "status": "aberto",
      "nota_status": "Solicitado por Lili na daily de 10/mar/2026"
    },
    {
      "id": "alerta034",
      "data": "2026-03-09",
      "titulo": "AA taxa de fechamento semanal em 3% — possível queda na conversão do closer",
      "critica": "Meta Aquisição 09/03: AA Fechada/Realizadas semanal = 3%/57% = 52% da meta. Isso significa que de 27 RRs realizadas nesta semana, praticamente nenhuma escola fechou. Pimentel identificou Marcele como closer com desempenho ruim na semana anterior. Ainda é semana 1 e pode ser ruído estatístico, mas se se repetir na semana 2, o impacto no bolsão de AA e na receita de março é significativo.",
      "acao_sugerida": "Pimentel monitorar taxa de fechamento AA semana a semana. Se taxa se mantiver abaixo de 40% na semana de 09/mar, diagnóstico pontual com Marcele até 13/mar. Não alterar processo antes de confirmar padrão em 2 semanas consecutivas.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta",
      "fonte": "Meta Aquisição 09/03/2026"
    },
    {
      "id": "alerta031",
      "data": "2026-03-08",
      "titulo": "Cerco Mágico começa 09/mar sem confirmação de S1 concluído (8 itens)",
      "critica": "O Cerco Mágico começa AMANHÃ (09/mar) mas os 8 itens do checklist S1 — com prazo oficial de 14/mar — não foram confirmados como concluídos em nenhuma daily da semana. Sem setup: chips WA não comprados, arte da Revista não fechada, freelancers não contratados, QR code não criado, bases não segmentadas. O Cerco começa sem infraestrutura completa.",
      "acao_sugerida": "Karina e Vitória: confirmar status atual dos 8 itens S1 na segunda 09/mar antes da daily. Itens críticos para execução imediata: chips WA (t089) e freelancers (t087). Itens críticos para semana: segmentação de base (t090) e arte Revista (t088). Comunicar Pedro com status real.",
      "prioridade": "critica",
      "dri": "Karina Machado",
      "status": "aberta",
      "fonte": "Análise Cerco Mágico 2026 — sessão Claudete 08/03"
    },
    {
      "id": "alerta032",
      "data": "2026-03-08",
      "titulo": "HT PART Renovação encerrou semana com déficit irrecuperável — 79% RR/SDR",
      "critica": "A semana de 03-06/mar encerrou com HT PART Renovação em 79% do RR/SDR semanal. Na daily 06/mar, as 22 RRs necessárias no último dia eram matematicamente impossíveis. O deficit da semana vai acumular em março se não houver correção imediata na semana de 09/mar. É o maior baldinho de Renovação e está sistematicamente abaixo da meta.",
      "acao_sugerida": "Pimentel analisa base HT PART antes de segunda (t100). Nath executa disparo MKT HT PART na segunda 09/mar (t100). Nath entrega visão do funil de renovação (t070) até 10/mar para diagnóstico de onde está trancando.",
      "prioridade": "critica",
      "dri": "Ana Paula Pimentel",
      "status": "aberta",
      "fonte": "Daily Gestão Comercial 06/03/2026 + análise sessão Claudete 08/03",
      "nota_status": "09/03: RR/SDR HT PART semana 1 = 1,32/1,60=83%. Disparo HT PART 5-30k iniciado por Vitória hoje (t100 concluído). Análise Pimentel confirmada. Semana de recuperação em curso. Monitorar RR/SDR diariamente para avaliar se disparo gerou volume."
    },
    {
      "id": "alerta033",
      "data": "2026-03-08",
      "titulo": "Calix perdendo efeito em AA e Retração — enriquecimento previsto para maio, Cerco começa em março",
      "critica": "Daily 06/03 confirmou que o Calix está perdendo efetividade nas bases de AA e Retração. O enriquecimento de base estava planejado para maio. O Cerco Mágico começa em março com as duas frentes de maior ROI histórico (AA: insight002) operando com ferramenta degradada. Gap de 2 meses sem solução.",
      "acao_sugerida": "Luana avaliar antecipação do enriquecimento de base para março/abril — não pode esperar maio com o Cerco em execução. Alternativa: enriquecimento pontual das 130 escolas AA isoladas por Pimentel (sem contato em 2026) como teste prioritário antes do disparo. DRI: Luana.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberta",
      "fonte": "Daily Gestão Comercial 06/03/2026 + análise sessão Claudete 08/03"
    },
    {
      "id": "alerta029",
      "data": "2026-03-03",
      "critica": "Processo de Boas-Vindas em risco crítico. Lili alertou na daily 03/03 que falha nessa etapa pode comprometer metade da receita anual. Escolas fechadas que não progridem no onboarding viram receita perdida. Time ainda sem acompanhamento estruturado do processo. Nath solicitada a criar controle.",
      "dri": "Liliane Mathias",
      "prioridade": "critica",
      "acao_sugerida": "Lili e Nath criarem acompanhamento semanal de Boas-Vindas (t082). Pimentel levantar volume com Maria Laísa (t084). Avaliar se enriquecimento pode ser suspenso temporariamente para alocar pessoal.",
      "status": "aberta",
      "fonte": "Daily Gemini 03/03/2026"
    },
    {
      "id": "alerta030",
      "data": "2026-03-03",
      "critica": "HT PÚB Renovação com zero fechamentos nesta semana (Tx fechadas/realizadas = 0). Duas reuniões realizadas, nenhuma convertida. Segmento tem RR/SDR de 2,40 (acima da meta), mas sem conversão de fechamento na semana de 03/03. Pode ser início de mês, mas merece monitoramento imediato.",
      "dri": "Karina Machado",
      "prioridade": "alta",
      "acao_sugerida": "Kaka verificar o que aconteceu nas 2 RRs de HT PÚB desta semana: objeção de fechamento, missing follow-up ou timing? Acompanhar diariamente até a semana fechar.",
      "status": "aberta",
      "fonte": "Daily Meta Aquisição 03/03/2026",
      "nota_status": "08/03: HT PUB bateu meta de RR na semana de 03-06/mar (daily 05-06/03). Monitorar conversão de fechamento na semana de 09/mar."
    },
    {
      "id": "alerta025",
      "data": "2026-03-02",
      "critica": "Concorrencia abriu marco com 45% de fechadas/realizadas vs 58% em fevereiro - queda de 13pp sem causa documentada. Com 1 SDR a menos e bolsao herdado de fev, risco de degradacao continuada.",
      "dri": "Ana Paula Pimentel",
      "prioridade": "critica",
      "acao_sugerida": "Pimentel entregar doc de investigação histórica da queda (t103, prazo 13/mar). Verificar: alunos/escola em Concorrência, tx fechamento pós-RR março vs fevereiro, composição carry-over vs novas. A/B copy 'diminuição de trabalho' confirmado (insight070) — copy digital resolvida. Problema pode estar no pós-RR.",
      "status": "aberta",
      "nota_status": "08/03: A/B copy resolvido (insight070). Meta de alunos Concorrência ainda em 13%. Investigação histórica em andamento (t103). Alerta mantido."
    },
    {
      "id": "alerta026",
      "data": "2026-03-02",
      "critica": "HT PART Renovacao com RR/SDR de 1,60 vs meta de 2,0 - gap de 0,40pp. Situacao piorou: daily 06/03 mostra 79% RR/SDR semanal com 22 RRs necessarias no ultimo dia — impossivel de recuperar. Semana encerrada em deficit.",
      "dri": "Ana Paula Pimentel",
      "prioridade": "critica",
      "acao_sugerida": "Pimentel analisa base HT PART antes de segunda (t100) para direcionar disparo MKT 09/mar (t100). Nath executa disparo. Semana de 09/mar é a janela de recuperação.",
      "status": "aberta",
      "nota_status": "09/03: Disparo HT PART Renov 5-30k (etapas SDR + descarte + perdido, exceto críticas) iniciado por Vitória — ação do dia na Meta Aquisição. RR/SDR HT PART semana 1: 1,32/1,60=83%. Realizadas: 38/59=65% (semana 1 de 4). Meta receita comercial 251% YTD. Semana de recuperação em curso — monitorar diariamente."
    },
    {
      "id": "alerta023",
      "data": "2026-02-27",
      "titulo": "WA pessoal da Lili bloqueado — canal de ativação 1-a-1 sem protocolo de contingência",
      "critica": "Número da Lili bloqueado por 24h após Operação Lili Doce. Chip novo tem mesmo risco de bloqueio por volume. Operação de hoje (48 escolas) está em risco de canal. Sem rotação de chips ou limite diário documentado, o problema vai se repetir em cada operação de ativação em escala.",
      "acao_sugerida": "Pedro compra chip temporário hoje (t058). Vit testa Blip como aviso de mimo (t062). Definir protocolo: máximo de mensagens por número por dia, chips em rodízio, Blip para informativo e WA para pedido de lista.",
      "prioridade": "alta",
      "dri": "kaka",
      "status": "aberta"
    },
    {
      "id": "alerta024",
      "data": "2026-02-27",
      "titulo": "Saída de 3+ pessoas de Renovação em fevereiro — impacto em capacidade de março sem análise",
      "critica": "Renovação perde 3 pessoas + Lari este mês (além de Isabele e Poli para Relacionamento). Time está em 77% da meta empresa. Nath expressou preocupação explícita com estabilidade. Nenhuma análise de impacto em RR/SDR de março foi feita ainda.",
      "acao_sugerida": "Nath recalcula headcount real e impacto em RR/SDR esperado para março (t063). Trazer para Pedro na segunda. Se houver gap crítico de capacidade, Pedro decide sobre aceleração de contratação.",
      "prioridade": "alta",
      "dri": "nath",
      "status": "aberta"
    },
    {
      "id": "alerta018",
      "data": "2026-02-26",
      "titulo": "Copy de Outbound (playlist emocional) tem CPL 7,4x acima do benchmark — reformulação urgente antes do próximo ciclo",
      "critica": "Outbound Playlist 23/02: R$721,44 para 2 levantadas. CPL R$360,72 vs benchmark R$48,60. Copy de 'experiência emocional do filho com trilha sonora' gera cliques (18 = 1,35%) mas não levantadas (2 = 0,15%). Ratio 9:1 clique:levantada confirma: o conteúdo ressoa como entretenimento, não como proposta comercial. Se o próximo ciclo de Outbound repetir essa abordagem, estamos queimando orçamento de forma previsível.",
      "acao_sugerida": "Luana e Vitória: desenvolver nova copy de Outbound com argumento de negócio (ROI, diferenciação, exclusividade) antes do próximo disparo. Ver insight043 para diretriz. Nenhum disparo de Outbound com copy emocional/playlist enquanto nova abordagem não for testada.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberta",
      "evidencia": "Mar/03 Playlist Renovacao Publica e Particular: 0 levantadas (objetivo = Levantada). Confirma que Playlist nao funciona para Renovacao como oferta de levantada. Ver insight111.",
      "ultima_atualizacao": "2026-03-13T08:51:54.377989"
    },
    {
      "id": "alerta020",
      "data": "2026-02-26",
      "titulo": "Blip ligações — risco de spam sistêmico: gestora nega → contato bloqueado permanentemente",
      "critica": "Identificado na daily 26/02: Blip para ligações exige confirmação da gestora antes de ligar. Se ela nega, o contato é marcado como spam permanentemente. Isso pode estar destruindo silenciosamente a base de contatos antes de qualquer abordagem real. Teste com SDR externa em andamento mas resultado ainda desconhecido. Enquanto não houver validação, risco real de dano irreversível à base.",
      "acao_sugerida": "Pimentel/Nath: suspender uso de Blip para ligações até resultado do teste externo. Avaliar impacto retroativo: quantos contatos já foram bloqueados. Definir protocolo de uso antes de reativar.",
      "prioridade": "critica",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta021",
      "data": "2026-02-26",
      "titulo": "Time de Concorrência perde 1 pessoa em março — base recomeça do zero com capacidade reduzida",
      "critica": "Identificado na daily 26/02: 1 pessoa do time de Concorrência (3 no total) não será efetivada. Sai no mês seguinte. Além da redução de capacidade, a desmotivação pode contaminar outra colega do time. Em março, a base de Concorrência recomeça do zero com time menor e possivelmente desmotivado.",
      "acao_sugerida": "Pimentel avaliar impacto na meta de Concorrência de março e ajustar expectativa. Considerar medidas de gestão para não contaminar o time restante. Planejar onboarding/recomposição se necessário.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta012",
      "data": "2026-02-25",
      "titulo": "Goto aparece como spam — taxa de contato AA contaminada por infraestrutura",
      "critica": "Chamadas da Goto aparecem como spam nos telefones das gestoras. Testado pela própria Lua em 24/02. Isso significa que toda a análise de taxa de contato de AA feita até hoje pode estar subestimando o problema real — o bloqueio é de infraestrutura, não de lista ou copy. Escolas que não atenderam podem não ter visto como 'não interesse', mas como spam bloqueado automaticamente.",
      "acao_sugerida": "Lua testar hoje 1 SDR ligando de fora da Goto (celular pessoal/número alternativo) para escolas AA que não responderam. Comparar taxa de contato vs Goto. Nath isolar métricas: contatos via WhatsApp vs Goto, taxa de cada. Resultado em D+2.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "em_execucao",
      "atualizacao_25_02": "Teste confirmado para 26/02: Tati isolada para ligar fora da Goto. Lili confirmou com Lua às 19:15 via Google Chat. Resultado esperado em D+1 (26/02).",
      "nota_status": "02/03: Nath ativou Bina na GOT. Investigacao spam com Lua em andamento (t027)."
    },
    {
      "id": "alerta013",
      "data": "2026-02-25",
      "titulo": "Copy da caneca sem CTA de condicionamento — expectativa errada na escola",
      "critica": "Uma escola foi à RR com o Closer esperando a caneca como brinde garantido, não como benefício condicional à adesão. A copy atual não deixa claro que a escola precisa agir para receber o mimo. Isso enfraquece o argumento do Closer no fechamento e pode estar acontecendo em mais escolas silenciosamente.",
      "acao_sugerida": "Vitória/Kaka revisar copy do disparo de 25/02 antes de enviar: incluir CTA explícito de condicionamento ('para garantir a sua caneca, basta...'). Regra permanente: todo disparo de mimo físico deve ter o condicionamento explícito na mensagem.",
      "prioridade": "alta",
      "dri": "Karina Machado",
      "status": "aberta"
    },
    {
      "id": "alerta014",
      "data": "2026-02-25",
      "titulo": "Script SDR com 'como foi?' ainda ativo para escolas com feedback negativo",
      "critica": "A pergunta 'como foi sua experiência?' está no discurso SDR de 2025 e 2026. Para escolas com feedback negativo registrado no card, ela abre objeção imediata que o SDR não consegue reverter — e que o Closer vai herdar na reunião. A investigação de Bebel documentou isso em dois ciclos consecutivos sem que o script fosse corrigido.",
      "acao_sugerida": "Lua implementar filtro por histórico de feedback antes do contato SDR: escola com flag negativo não recebe a pergunta 'como foi?' — SDR abre com Instagram ou argumento de benefícios diretamente. Treinamento pontual com supervisores, não reciclagem geral do script.",
      "prioridade": "alta",
      "dri": "Luana",
      "status": "aberta"
    },
    {
      "id": "alerta015",
      "data": "2026-02-25",
      "titulo": "Email pós-reunião do Closer é brochure — não prepara escola para aprovação interna",
      "critica": "O template atual de email pós-RR apresenta a Estante Mágica do zero para uma escola que acabou de fechar. Não inclui argumentos para a coord apresentar ao diretor/financeiro que não participou da reunião. Isso cria um vácuo no momento mais crítico da aprovação interna — e pode estar contribuindo para o gap de bolsão (fechada sem converter).",
      "acao_sugerida": "Pimentel reescrever template de email pós-RR como kit de aprovação interna: resumo personalizado da conversa + três argumentos para o diretor/financeiro + vídeo de envio por foto/áudio + oferta com prazo. Brochure genérico vira anexo opcional. Implementar antes do próximo ciclo de reuniões de AA.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta016",
      "data": "2026-02-25",
      "titulo": "LGPD como bloqueio de conversão emergindo — 3 casos simultâneos sem processo padronizado",
      "critica": "Três escolas simultâneas se recusaram a compartilhar dados de alunos por questão de LGPD em 25/02. Cada caso está sendo resolvido individualmente (1 em Tech, 1 negociando acesso direto, 1 com nova RR). Sem fluxo padronizado, cada novo caso consome tempo de Wydi/Pimentel e pode travar a conversão por dias. Se o volume escalar, vira gargalo sistêmico de bolsão.",
      "acao_sugerida": "Pimentel mapear os 3 casos ativos e criar fluxo de resolução padrão: (1) escola quer subir ela mesma → protocolo Tech já; (2) escola recusa categoricamente → escalada com argumento jurídico/contratual. Prazo: antes de março. Incluir script de prevenção para o Closer usar na RR.",
      "prioridade": "alta",
      "dri": "Ana Paula Pimentel",
      "status": "aberta"
    },
    {
      "id": "alerta017",
      "data": "2026-02-25",
      "titulo": "24% das levantadas de AA descarte são registros 'Duplicada' — base inflando resultados",
      "critica": "No resultado final de c003 (caneca AA 25/02), 6 de 25 levantadas (24%) vieram de registros classificados como 'Duplicada' na base. Se são registros duplicados da mesma escola, o número real de levantadas únicas é 19, não 25 — e o CPL está subestimado em ~32%. Enquanto não houver limpeza, todo relatório de campanha de AA descarte reporta resultado inflado.",
      "acao_sugerida": "Vitória identificar se as 6 'Duplicada' são escolas repetidas no sistema ou um status de descarte diferente. Se forem duplicatas de registro, limpar a base antes do próximo ciclo de disparos de AA e ajustar número oficial de levantadas de c003.",
      "prioridade": "alta",
      "dri": "Vitória Riente",
      "status": "aberta"
    },
    {
      "id": "alerta001",
      "data": "2026-02-24",
      "titulo": "SDR 12%: efetividade a 2,5x abaixo da meta",
      "critica": "Efetividade SDR precisa ser atualizada no painel para validar o cenário real. Sem esse dado, o diagnóstico de capacidade fica cego.",
      "acao_sugerida": "Nath atualizar a efetividade SDR no dashboard hoje e confirmar fonte (data e período).",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberta",
      "nota_status": "09/03: RR/SDR por baldinho (Meta Aquisição 09/03): HT PART 1,32/1,60=83%, HT PUB 1,80/2,40=75%, AA 0,86/0,75=115%✅, Concorrência 0,55/0,50=110%✅, Retração 0,43/0,64=68%, Novas 0,32/0,46=77%. AA e Concorrência acima da meta; Retração e HT persistem abaixo. Efetividade global heterogênea — alerta mantido."
    },
    {
      "id": "alerta004",
      "data": "2026-02-24",
      "titulo": "Retração semana: RR/SDR em 40% — março começa em débito",
      "critica": "O mês de fevereiro de Retração está verde (107% RR/SDR), mas a semana de 24/02 está em 0,20/0,50 (40%) no Baldinho Retração. O resultado mensal está sendo sustentado por estoque de semanas anteriores. Se esse ritmo se repetir em março, o mês começa morto.",
      "acao_sugerida": "Nath verificar esforço de SDR em Retração nessa semana: é inércia do time, Ax ou decisão de manter o 0,5 por conta de meta já batida? Definir ritmo mínimo para semana que vem.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberta",
      "nota_status": "09/03: Retração RR/SDR 0,43/0,64=68% da meta YTD. Tx fechadas/realizadas: 50%/62%=81%. Realizadas: 10/56=78% YTD. Meta alunos 1.088/4.355=110%✅. Melhora vs 40% de fev mas ainda estruturalmente abaixo de meta. Nath não entregou diagnóstico de causa. Alerta mantido."
    },
    {
      "id": "alerta005",
      "data": "2026-02-24",
      "titulo": "Renovação LT Part: RR/SDR travado em 1,42 há 5 dias",
      "critica": "De 19/02 a 24/02, o RR/SDR da base LT Part ficou em 1,42 — mesmo número, todos os dias. Ou os dados não estão sendo atualizados corretamente, ou o esforço está estagnado. Meta é 2,0.",
      "acao_sugerida": "Nath verificar se o dado está sendo registrado corretamente. Se sim, identificar qual ação específica pode mover o RR/SDR LT antes do fechamento do mês.",
      "prioridade": "alta",
      "dri": "Nath Ferreira",
      "status": "aberta",
      "nota_status": "09/03: LT PART em 3/30 convertidas = 10% da meta mensal. Meta marketing LT Part: R$8.945/R$98.649 = 9%. A frente inteira está em risco crítico — não apenas o RR/SDR, mas as convertidas e a receita de marketing. Ação de MKT urgente para LT PART não apareceu nas ações do dia de 09/03. Alerta escalado em urgência."
    },
    {
      "id": "alerta006",
      "data": "2026-02-24",
      "titulo": "Ativação bolsão em 61% da meta — receita fechada não está virando bolsão",
      "critica": "A conversão para Closer está acima da meta, mas a ativação (bolsão) está em 61%. O esforço de SDR e Closer está funcionando — o gargalo é o último elo da cadeia: escola fecha e não converte para bolsão. Essa é a receita que está 'dentro de casa' e não realizada. Com 4 dias úteis até 28/fev, 40 mimos devem ser enviados hoje para destravar esse funil.",
      "acao_sugerida": "Karina garantir envio dos 40 mimos para bolsão hoje (via Pix com Rafa se cartão/iFood travar). Confirmar status de cada envio no D+1. Meta: 10 em 10 agendamentos de bolsão recebem mimo antes do contato de ativação.",
      "prioridade": "critica",
      "dri": "Karina Machado",
      "status": "aberta",
      "atualizacao_25_02": "Mimos enviados: 27 (Pimentel) + 28 (Wydi) = ~55 no dia. Taxa de reversão de sumiço: 20% (4/20). Dia comprometido por 2 de 5 ativadores ausentes (40% capacidade) + parada para alinhamento operacional. 10 retornos programados para 26/02 com gestão/secretaria. Benchmark registrado: insight039."
    },
    {
      "id": "alerta007",
      "data": "2026-02-24",
      "titulo": "Tags Blip/HubSpot inválidas — medição de levantadas de campanha inflada em até 4x",
      "critica": "Tag de marketing (rastreia todas as escolas que receberam disparo) está sendo usada como proxy de levantadas. Resultado: número de 54 levantadas da caneca 23/02 é não confiável — sobreposição com ações anteriores infla o dado. Todo ROI de campanha calculado com esse número é inválido. Decisões de budget, copy e segmentação baseadas nesse número estão contaminadas.",
      "acao_sugerida": "Vitória criar tag separada 'disparo_recebido' (distinta da tag Heróis de levantada confirmada) antes do próximo disparo. Revisar retroativamente levantadas das últimas campanhas usando apenas tag Heróis como denominador. Nunca reportar tag de marketing como proxy de levantadas.",
      "prioridade": "critica",
      "dri": "Vitória Riente",
      "status": "aberta"
    },
    {
      "id": "alerta009",
      "data": "2026-02-24",
      "titulo": "Fluxo de atribuição de levantadas inexistente — leads quentes perdidos sistematicamente",
      "critica": "27 escolas de renovação levantaram a mão em 23/02 e não receberam contato no mesmo dia. Tickets Blip fechados antes do SDR entrar em contato. O processo atual de distribuição geral automática não está funcionando. Cada lead quente não atendido em 2h tem probabilidade de conversão drasticamente reduzida.",
      "acao_sugerida": "Vitória criar filas Blip por baldinho hoje. Pimentel fornecer nomes dos supervisores por baldinho até 10h. Supervisor com acesso ao portal Blip prioriza atribuição 8h-9h. Confirmar funcionamento antes do disparo de 25/02.",
      "prioridade": "critica",
      "dri": "Vitória Riente",
      "status": "aberta"
    },
    {
      "id": "alerta011",
      "data": "2026-02-24",
      "titulo": "Outbound WhatsApp com 0,15% de levantadas",
      "critica": "O disparo Outbound teve 2 levantadas em 1.336 entregues (0,15%). Isso é desempenho estruturalmente baixo e indica falha de segmentação, lista ou copy. Continuar disparando nessa base sem correção consome orçamento e gera custo de oportunidade.",
      "acao_sugerida": "Vitória revisar segmentação e copy do Outbound; testar micro-lote com lista qualificada antes de novo disparo em massa.",
      "prioridade": "alta",
      "dri": "Vitoria",
      "status": "aberta"
    },
    {
      "id": "alerta050",
      "titulo": "Impulsionar Fevereiro estourou 91% do orcamento (R$18.312 vs R$9.607 orcado) sem registro de aprovacao",
      "tema": "campanha",
      "data_criacao": "2026-03-13",
      "status": "aberto",
      "prioridade": "alta",
      "dri": "Vitoria",
      "evidencia": "Aba Orcamentos Mes a Mes: Fev Impulsionar orcado R$9.606,50, realizado R$18.311,79, saldo -R$8.705,29. Marco: R$2.100,75 de R$9.606,50 (22% usado). Sem registro de aprovacao para o estouro de fevereiro.",
      "acao_sugerida": "Pedro e Vitoria: definir teto semanal para Impulsionar ou exigir aprovacao de Pedro para qualquer valor acima do orcado. Revisar o que gerou o estouro de R$8.705 em fevereiro e avaliar se houve ROI equivalente.",
      "contexto": "Analise planilha Vit — Disparos e Controles de Marketing Jan-Mar/2026"
    }
  ],
  "indices_digest": {
    "temas_disponiveis": [
      "sdr",
      "base",
      "geral",
      "rr_sdr",
      "renovacao",
      "copy",
      "concorrencia",
      "campanha",
      "outbound",
      "retracao",
      "funil",
      "whatsapp",
      "anos_anteriores",
      "canal",
      "todos",
      "novas",
      "comportamento",
      "baldinho",
      "oferta",
      "bolsao_ativacao",
      "copy_e_mensagem",
      "operacoes_comerciais",
      "operacao",
      "processo_sdr",
      "performance",
      "renovacao_lt",
      "bolsao",
      "base_concorrencia",
      "aa_fechadas",
      "wpp_disparos",
      "timing",
      "segmentacao",
      "modelo_operacional",
      "escolas_saturadas",
      "copy_escrita",
      "bolsao_2025",
      "time_de_vendas",
      "segmentacao_de_base",
      "sdr_cadencia_de_contato",
      "risco",
      "renovacao_ht_part",
      "qualificacao_de_base",
      "protocolo_de_fechamento",
      "pitch_closer",
      "operacoes_manuais",
      "operacional",
      "mkt_renovacao",
      "meta",
      "marketing",
      "ht_pub",
      "funil_novas_escolas",
      "ferramenta",
      "escolas_saturadas_alto_valor",
      "escolas_fechadas_nao_convertidas",
      "copy_whatsapp",
      "copy_e_mail",
      "canal_whatsapp",
      "campanhas_outbound",
      "base_retracao",
      "base_ht_publica",
      "base_de_contatos",
      "base_aa",
      "ativacao",
      "analise_de_bolsao",
      "acao_1a1"
    ],
    "itens_indexados": 160
  }
};
