window.WATCHDOG_TODOS = [
  {
    "id": "t179",
    "task": "Nath: calcular custo por aluno cadastrado por frente (LT PART vs LT Pública vs HT Pública) E incluir análise de ticket médio por convertida em LT PART — identificar se escolas maiores da base de 311 alunos cadastrados (documento 16/03) ainda não foram trabalhadas. ADICIONAR: confirmar se documento de 16/03 é acumulado do mês ou semanal — inconsistência com dados do alerta056 (que registrava 16 convertidas vs 9 neste documento) precisa ser esclarecida antes de 18/03.",
    "comment": "Documento registra 311 alunos cadastrados em LT PART (vs 451 do alerta056). Inconsistência pode ser de data do snapshot ou versão diferente do arquivo. Ticket médio implícito atual: R$2.942/convertida vs R$3.288 necessário pela meta.",
    "owner": "Nath Ferreira",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t180",
    "task": "Pimentel: usar Notebook LM para analisar audios de no-show em Renovacao e identificar padroes de cancelamento/ausencia",
    "comment": "Decisao tomada na daily 13/03. Pedro recusou aceitar o argumento de escola ocupada sem analise mais profunda. 16 mimos nao resolveram o comparecimento (insight125). Objetivo: identificar padrao de quando e por que gestoras agendam mas nao aparecem.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t181",
    "task": "Karina e Vitória: avaliar janela de oportunidade para disparo adicional de Low Touch com ação de vídeo — atualizar para incluir bases públicas (HT PÚB e LT PÚB) conforme decisão da daily 17/03",
    "comment": "Tarefa t181 era apenas LT com vídeo na semana de 16/03. A daily 17/03 expandiu o escopo: bases públicas foram incluídas na estratégia de disparo. Prazo atualizado para semana que vem.",
    "owner": "Kaka",
    "date": "19/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t182",
    "task": "Pedro e Karina: enviar briefing do webinar com Antonia Burk para Pimentel (datas, tema, formato)",
    "comment": "Proximo passo explicito da daily 13/03. Webinar confirmado para a primeira semana de abril. Sem briefing na proxima segunda, Pimentel nao pode iniciar planejamento de divulgacao.",
    "owner": "Pedro",
    "date": "16/mar",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": "2026-03-17T23:53:00"
  },
  {
    "id": "t183",
    "task": "Vitoria: confirmar status do disparo WA de Retração (base ampliada) — verificar se foi executado e qual o resultado de abertura/levantada até agora",
    "comment": "Tarefa original criada para execução até 18/03. Documento de hoje mostra Retração mensal com RR/SDR em 71% da meta e realizadas em 85%. A semana atual tem sinais positivos (semanal verde) mas o mês ainda precisa de recuperação. Confirmar se o disparo saiu e qual retorno inicial.",
    "owner": "Vitoria",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t184",
    "task": "Lili: dar acesso a Vitoria a planilha sendo fechada com Nath — insumo para analise de custo medio de oferta no CPL",
    "comment": "Proximo passo explicito da daily 13/03. Vitoria precisa da planilha para calcular custo medio de vale-presente e sem trabalho e incorporar ao CPL para comparacao de ROI (insight123).",
    "owner": "Lili",
    "date": "13/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t185",
    "task": "Vitoria: calcular custo medio do vale-presente e do sem trabalho no CPL — apresentar na proxima daily",
    "comment": "Proximo passo da daily 13/03. Depende de t184 (acesso a planilha da Lili). CPL canal + custo medio da oferta por levantada = CPL total. Decisao estrategica: incluir custo da oferta no CPL para comparacao de ROI.",
    "owner": "Vitoria",
    "date": "16/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t186",
    "task": "Karina: confirmar com designers ate 14/03 se pelo menos um aceitou a arte da revista e quando entrega",
    "comment": "Karina confirmou na daily que entraria em contato hoje. Se nenhum designer disponivel, escalar para Pedro imediatamente. Arte da revista e o item com maior lead time do Cerco Magico. Conectada a alerta054.",
    "owner": "Kaka",
    "date": "14/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t187",
    "task": "Pimentel: mapear causa do underperformance de HT PÚB nesta semana (RR/SDR 52% semanal, Realizadas 70%) — verificar agenda closers, fila de leads e abastecimento de topo. Garantir pelo menos 11 realizadas na semana de 18/03 para recuperar RR/SDR mensal para patamar mínimo de 75%. CONTEXTO ATUALIZADO: semana de 16/03 registrou 8 realizadas vs meta 11 (70%) e RR/SDR 1,20 vs 2,29 (52%) — a recuperação parcial não foi suficiente.",
    "comment": "Alerta057 (zero absoluto na semana anterior) parcialmente resolvido: saiu do zero para 8 realizadas. Mas RR/SDR mensal continua em 63% da meta e a frente precisa de aceleração real na semana de 18/03.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t188",
    "task": "Nath: calcular número médio de alunos por escola fechada em Concorrência em março e identificar concentração de escolas pequenas no bolsão ativo — insumo para redistribuição de base (pendente do alerta037)",
    "comment": "Concorrência: 810/2.963 alunos (55% YTD) com Realizadas em 103% e RR/SDR em 111%. O gargalo não é volume de reuniões — é tamanho médio das escolas fechadas. Meta implícita é ~89 alunos/escola; necessário verificar se o bolsão ativo está concentrado em escolas menores.",
    "owner": "Nath Ferreira",
    "date": "19/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t189",
    "task": "Vit checar respostas do disparo de vídeo de ontem em renovação LT low touch e reportar evolução de levantadas (baseline: 9→13)",
    "comment": "Prazo inferido: urgente, ação do dia. Resultado do disparo de ontem — monitoramento imediato é crítico para calibrar próximo lote.",
    "owner": "Vitoria",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t189",
    "task": "Vit ajustar cálculo da meta de Marketing usando receita do ano anterior por escola (não bucket fixo de R$109/aluno) e sugerir ajuste no texto do vídeo ao grupo",
    "comment": "Prazo inferido: 2 dias úteis. Impacta acurácia do Meta Marketing que hoje oscilou de 108% para 86% dependendo do critério. Decisão de metodologia foi tomada na daily por Lili.",
    "owner": "Vitoria",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t189",
    "task": "Nath verificar as três escolas de concorrência com problema de entrada (incluindo escola de 200 alunos e fechada de 60 alunos de ontem) e retornar com diagnóstico e caminho de resolução",
    "comment": "Prazo inferido: 2 dias úteis. Meta de alunos em concorrência em 55% — essas escolas são parte direta do gap. Alerta049 criado como consequência.",
    "owner": "Nath Ferreira",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t190",
    "task": "Lili levantar volume de escolas em HT Pública e LT Pública para o grupo, com segmentação para priorização do disparo de vídeo na semana de 23/mar",
    "comment": "Prazo inferido: urgente — disparo previsto para semana de 23/mar e calendário precisa ser definido até quinta 19/mar. Sem esse dado, Vit não consegue configurar a logística. Alerta048 associado.",
    "owner": "Lili",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t191",
    "task": "Kaká fazer dupla checagem na lista das 37 escolas para envio de mimos (bolsões) confirmando que nenhuma já recebeu antes, e alinhar com comercial após estruturação do envio",
    "comment": "Prazo inferido: envio adiado para amanhã (18/mar) conforme daily. Double check é pré-requisito do envio.",
    "owner": "Kaka",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t192",
    "task": "Kaká preparar vídeo de renovação para escolas não convertidas no setor comercial (segmento particular, foco em LT, seguindo resultado do disparo anterior)",
    "comment": "Prazo inferido: disparo faseado previsto para seg/ter/qua da semana de 23/mar — vídeo precisa estar pronto até quinta 19/mar para logística de Vit. Liliane Mathias solicitou formalmente na daily.",
    "owner": "Kaka",
    "date": "19/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t193",
    "task": "Ana Paula formalizar escopo de atuação de Rânia em negócios perdidos: quais bases, critério de priorização, volume estimado e meta de acompanhamento",
    "comment": "Prazo inferido: decisão estrutural — semana seguinte. Alerta051 criado. Sem escopo, alocação de Rânia não é rastreável.",
    "owner": "Ana Paula Pimentel",
    "date": "19/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t194",
    "task": "Claudete (ou Lili) consolidar calendário integrado de disparos da semana de 23/mar: sequência, volumes por lote, DRI de cada ação (vídeo LT PART faseado, vídeo HT/LT Pública, cerco mágico, anos anteriores)",
    "comment": "Prazo inferido: urgente — todas as ações convergem para semana de 23/mar e colisão de disparos é risco real. Alerta050 associado.",
    "owner": "Lili",
    "date": "19/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t195",
    "task": "Vit confirmar recebimento do ID da jornada com Lili/Ana e definir logística final do disparo (divisão em lotes manhã/tarde ou dias) para execução na semana de 23/mar",
    "comment": "Prazo inferido: pré-requisito operacional para disparo de seg 23/mar. Vit está aguardando ID da jornada conforme declarado na daily.",
    "owner": "Vitoria",
    "date": "19/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:51:00",
    "completedAt": null
  },
  {
    "id": "t196",
    "task": "Nath e Kaká: cruzar base de 451 alunos cadastrados em LT PART com histórico de convertidas — identificar se há concentração de escolas pequenas nas convertidas recentes (últimas 8-9 convertidas de março) vs convertidas iniciais, e mapear escolas grandes ainda não trabalhadas para priorização no próximo lote de abordagem",
    "comment": "Insumo direto para o alerta059. O ticket médio caindo de R$3.428 para R$2.640 ao longo do mês sugere que as escolas maiores ou já foram trabalhadas sem conversão ou estão sendo deixadas para depois. É necessário distinguir os dois casos para definir a ação correta.",
    "owner": "Nath Ferreira",
    "date": "19/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:52:00",
    "completedAt": null
  },
  {
    "id": "t197",
    "task": "Nath: incluir no próximo daily uma coluna de 'ritmo necessário/dia útil restante' para as frentes LT PART, HT PÚB, Retração e Concorrência — com base em dias úteis restantes no mês a partir de 17/03 (estimativa: 10 dias úteis até 31/03). Isso permite que a daily identifique em tempo real quando uma frente está em trajetória de não-fechamento.",
    "comment": "Dado estrutural que falta no documento atual: saber que LT PART está em 26% da meta não diz se é recuperável. Saber que precisa de 1,4 convertidas/dia útil com 10 dias restantes permite decisão imediata.",
    "owner": "Nath Ferreira",
    "date": "19/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Vitória: checar respostas do disparo de vídeo de ontem em renovação LT (levantadas subiram de 9 para 13) e reportar ao grupo",
    "comment": "Prazo inferido: urgente, resultado de ação de ontem. Fonte: próximas etapas sugeridas da daily 17/03.",
    "owner": "Vitoria",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Vitória: ajustar cálculo de meta de Marketing usando receita do ano anterior por escola (não R$109 fixo por aluno) e revisar/sugerir ajustes no texto do vídeo para o próximo disparo",
    "comment": "Prazo inferido: 2 dias úteis — insumo necessário antes do disparo da semana que vem. Duas ações agrupadas conforme a própria próxima etapa da daily.",
    "owner": "Vitoria",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Nath: verificar as 3 escolas de concorrência com problema de entrada — incluindo escola de 200 alunos e fechada de 60 alunos — e reportar status ao grupo",
    "comment": "Prazo inferido: urgente (hoje). Escola de 200 alunos tem impacto material na meta mensal de 55%. Fonte: próximas etapas sugeridas.",
    "owner": "Nath Ferreira",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Lili: levantar volume de escolas em HT pública e LT pública e trazer ao grupo para decisão de priorização do disparo de vídeo para bases públicas",
    "comment": "Prazo inferido: hoje — a decisão de expandir o disparo para público depende deste número e o disparo precisa ser logisticamente planejado antes da semana que vem.",
    "owner": "Lili",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Kaká: fazer double check na lista das 37 escolas (bolsões) para confirmar que nenhuma já recebeu mimo, e alinhar com comercial após estruturação do envio — disparo adiado para amanhã 18/03",
    "comment": "Item explícito nas próximas etapas. Envio foi adiado por volume e necessidade de Raísa focar na gráfica. Double check antes do envio é obrigatório.",
    "owner": "Kaka",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Identificar DRI para fornecimento do ID da jornada de disparo de vídeo e garantir entrega até 18/03 para que Vitória possa planejar logística do disparo faseado (seg/ter/qua semana que vem)",
    "comment": "Prazo inferido: urgente. Sem o ID, toda a logística do disparo de 2.800 escolas trava. Pedro deve definir DRI hoje. Relacionado ao alerta048.\n\nNormalizacao automatica: Dono ausente preenchido automaticamente com Lili.",
    "owner": "Lili",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Lili ou Pedro: definir data irrevogável para execução do Cerco Mágico em março, com gatilho explícito para não novo adiamento",
    "comment": "Prazo inferido: fim de semana (decisão estrutural). Segundo adiamento identificado. Relacionado ao alerta050. Sem data travada, a campanha pode não ser executada em março.",
    "owner": "Lili",
    "date": "19/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t198",
    "task": "Ana Paula Pimentel: mapear colaborador ausente em renovação pública — prazo de retorno e impacto em cobertura de HT PÚB — e reportar ao grupo",
    "comment": "Prazo inferido: urgente. Renovação pública zerou em reuniões realizadas na semana com colaborador ausente (alerta049). Informação necessária para decisão de cobertura emergencial.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t199",
    "task": "Vit enviar Top 30 escolas de anos anteriores para Kaká (com atributos de personalização: nome de coordenadora, histórico) para seleção e triagem com supervisora Luana",
    "comment": "Kaká solicitou a lista na daily de 16/03. Pedro gravará os vídeos personalizados após Kaká negociar a lista com Luana para filtrar escolas insatisfeitas. Prazo inferido: 2 dias úteis.",
    "owner": "Vitoria",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t199",
    "task": "Kaká negociar lista Top 30 de anos anteriores com supervisora Luana, filtrando escolas insatisfeitas, e enviar lista final a Pedro com nome de coordenadora e informações de personalização",
    "comment": "Depende de t196 (Vit entregar a lista bruta). Pedro aguarda lista final para gravar os vídeos. Prazo inferido: 1 dia útil após recebimento da lista de Vit.",
    "owner": "Kaka",
    "date": "19/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t199",
    "task": "Pedro gravar vídeos personalizados para escolas Top 30 de anos anteriores (após receber lista final de Kaká com nome de coordenadora e histórico)",
    "comment": "Pedro se ofereceu para gravar na daily. Depende de t197. Prazo inferido para semana seguinte para viabilizar uso nos disparos da semana de 23/03.",
    "owner": "Pedro",
    "date": "21/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t199",
    "task": "Pimentel acionar força-tarefa do time de enriquecimento do Comercial para processar levantadas de mão acumuladas na fila de heróis (200+ respostas do disparo de vídeo)",
    "comment": "Decisão da daily: força-tarefa sugerida por Lili para não perder oportunidades. Sem DRI definido na reunião — Pimentel é a gestora do Comercial responsável pela frente. Urgente: leads quentes esfriam rapidamente.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t200",
    "task": "Vit confirmar com Manassés se erro de passagem de levantadas para o HubSpot foi corrigido e quantas levantadas ficaram sem registro — reportar diagnóstico ao grupo",
    "comment": "Manassés identificou o erro na daily de 16/03. Sem confirmação de correção e auditoria do que ficou sem registro, o CRM está com dados comprometidos. Prazo: hoje (urgente).",
    "owner": "Vitoria",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t201",
    "task": "Lili e Vit amarrar universo e foco da máquina de frilas para validação de contatos WA (toda a base de 45k vs. residual) e nomear DRI operacional no Comercial",
    "comment": "Decisão tomada na daily: escopo primeiro, depois alocação no Comercial. Prazo inferido: 2 dias úteis. Custo envolvido: R$4.500 para disparo utilitário — decisão não pode ficar indefinida.",
    "owner": "Lili",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t202",
    "task": "Kaká verificar com Luiz quem em Operações pode ser ponto focal com a gráfica para a Revista Estante Mágica, evitando sobrecarga de Vit",
    "comment": "Vit expressou preocupação com sobrecarga na operação da revista. Kaká concordou em verificar com Luiz. Decisão tomada na daily sem prazo — inferido como 2 dias úteis.",
    "owner": "Kaka",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t203",
    "task": "Kaká reportar status dos frilas de conteúdo: volume realizado vs. esperado, prazo de normalização e status do contrato — definir plano B se ritmo não normalizar até 20/03",
    "comment": "Alerta061 aberto. Frilas em adaptação, contrato pendente, volume abaixo do esperado desde sexta-feira (13/03). Prazo inferido: 2 dias úteis.",
    "owner": "Kaka",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t204",
    "task": "Bebel atualizar receita por aluno no book para permitir cruzamento de investimento vs. retorno por frente (LT Pública vs. LT Particular) e subsidiar decisão de rebalanceamento de esforço comercial",
    "comment": "Tarefa discutida na daily por Pedro e Lili. DRI: Bebel (explicitamente mencionada). Prazo inferido: semana seguinte, dado caráter analítico. Esta análise é insumo para decisão de alocação de esforço — contexto estratégico conectado a insight118 e alerta056.",
    "owner": "Bebel Bertuccelli",
    "date": "19/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t205",
    "task": "Vit programar disparos semanais de e-mail e WhatsApp para base de público que não converteu — plano pronto até final de março, programar execução para 17/03",
    "comment": "Vit se comprometeu na daily de 16/03 a programar os disparos para o dia seguinte (17/03). Plano já estava pronto. Tarefa de execução — verificar se foi concluída na próxima daily.",
    "owner": "Vitoria",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t206",
    "task": "Nath cobrar supervisores para ajustar tags de patrocínio incorretas até sexta-feira 20/03 — acompanhar e confirmar conclusão",
    "comment": "Próxima etapa explícita da daily de 16/03. Prazo: final da semana (sexta-feira 20/03), conforme Lili sugeriu na reunião. Nath é DRI de cobrança, supervisores executam a marcação.",
    "owner": "Nath Ferreira",
    "date": "20/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  },
  {
    "id": "t207",
    "task": "Lili discutir desafio de retração com Pimentel no one-on-one agendado para 17/03 e registrar encaminhamentos",
    "comment": "Lili agendou explicitamente a discussão sobre o desafio de retração para o one-on-one do dia seguinte (17/03) com Pimentel. Tarefa de verificar se encaminhamentos foram registrados.",
    "owner": "Lili",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:53:00",
    "completedAt": null
  }
];
