window.WATCHDOG_TODOS = [
  {
    "id": "t001",
    "task": "Investigar impacto do Calix vs discador manual nas abordadas de Concorrência e Outbound — trazer análise para o time",
    "comment": "Comparar performance de SDRs que usam Calix vs discador manual. Frente de concorrência tem apenas 3 pessoas. Suspeita adicional: impacto da migração para o Ax.",
    "owner": "Nath Ferreira",
    "date": "24/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t002",
    "task": "Enviar relatório da base de concorrência e bloqueios de disparo para a Vitoria",
    "comment": "Base tem 150 contatos de gestores nas etapas iniciais do funil (R$ 566). Disparo já decidido: incluir base de descarte, foco em trilha sonora/playlist.",
    "owner": "Nath Ferreira",
    "date": "23/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t003",
    "task": "Comunicar Raíça sobre apoio ao marketing na logística do chocolate (caráter experimental, sem expectativa de mudança de área)",
    "comment": "Ação envolve 41 escolas. Experimental esta semana.",
    "owner": "Ana Paula Pimentel",
    "date": "23/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t004",
    "task": "Treinar Raíça para a ação de logística do chocolate",
    "comment": "Dependente de t003 (Pimentel comunicar Raíça hoje).",
    "owner": "Kaka",
    "date": "24/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": 2,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t005",
    "task": "Investigar uso atual de mimos (chocolate) para agendamentos na base de retração",
    "comment": "Retração tem desafio histórico de agendamento. Entender se mimos estão sendo usados e com qual resultado.",
    "owner": "Ana Paula Pimentel",
    "date": "24/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t006",
    "task": "Verificar saldo de disparos restante (quanto ainda temos dos 5k)",
    "comment": "1.760 já gasto. Confirmar saldo antes de novos disparos.",
    "owner": "Vitoria",
    "date": "25/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t007",
    "task": "Entregar revisão das réguas e plano de low touch para renovação particular",
    "comment": "Bloqueio: Lili determinou que não serão geradas mais levantadas de renovação LT até este plano ser entregue. Frente está em 70%.",
    "owner": "Kaka",
    "date": "27/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": 3,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t008",
    "task": "Planejar cenourinha para o time de ativação",
    "comment": "Estratégia funcionou no mês anterior. Objetivo: impulsionar ritmo de abordadas. Valor confirmado: R$ 200 para a última semana.",
    "owner": "Ana Paula Pimentel",
    "date": "26/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t009",
    "task": "Enviar 40 mimos para bolsão hoje — 3 levas priorizadas",
    "comment": "Top prioridade Lili (24/02). Breakdown: (1) 10 prioritárias indicadas pela Pimentel; (2) 10 agendamentos do dia; (3) 20 demais fechadas e não convertidas. Se cartão/iFood travar, usar Pix via Rafa (financeiro). Confirmar status de envio D+1.",
    "owner": "Kaka",
    "date": "24/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": 1,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": null
  },
  {
    "id": "t010",
    "task": "Atualizar 'dinheiros na mesa' com as bases mais relevantes",
    "comment": "Lili solicitou na reunião de 23/02. Garantir que direção do time esteja alinhada com as bases de maior potencial.",
    "owner": "Nath Ferreira",
    "date": "24/fev",
    "tier": "done",
    "tierLabel": "Concluido",
    "warn": null,
    "done": true,
    "priorityRank": null,
    "updatedAt": "2026-02-24T00:00:00",
    "completedAt": "2026-02-24T00:00:00"
  },
  {
    "id": "t011",
    "task": "Fechar Doc de Planejamento de Mkt",
    "comment": "None",
    "owner": "Pedro",
    "date": "26/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t012",
    "task": "Garantir fluxo novo na Blip ligado antes dos disparos de 4a",
    "comment": "Criar filas específicas na Blip por baldinho + garantir que o fluxo de levantadas esteja integrado ao duplo aviso (fluxo + fila supervisor). Deve estar ativo ANTES dos disparos de quarta (t015 e t020). Pré-requisito: t013 (Pimentel fornecer supervisores por baldinho).",
    "owner": "Vitoria",
    "date": "24/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t013",
    "task": "Fornecer nomes dos supervisores de cada baldinho para Vitória configurar filas na Blip",
    "comment": "Input necessário para que Vitória crie as filas (t012). Enviar lista simples: baldinho → nome do supervisor.",
    "owner": "Ana Paula Pimentel",
    "date": "24/fev",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t014",
    "task": "Extrair do carteiro lista de 27+5 escolas caneca que responderam (com telefones) e enviar para Pimentel",
    "comment": "Apoio para t018 (Pimentel reabrir conversas). 27 renovação + 5 AA levantaram a mão no disparo de caneca (23/02). Vitória extrai do carteiro com números de telefone disponíveis. Entrega imediata — Pimentel precisa para reabrir conversas hoje.",
    "owner": "Vitoria",
    "date": "24/fev",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t015",
    "task": "Disparos de 4a (25/fev): caneca reforço + caneca descarte AA",
    "comment": "Resp Lili (base) + Mkt/Vitória (disparo). Dois disparos: (1) caneca reforço para base atual já disparada, com fluxo Blip ajustado; (2) caneca para base 'descarte' AA selecionada por Lili. Orçamento R$ 1.700. NÃO disparar para AA em fase SDR ativo (a018). Pré-requisito: t012 (fluxo Blip ligado).",
    "owner": "Vitoria",
    "date": "24/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t016",
    "task": "Reunião com time ID — definir argumento e sugestão de ação para FUP (fechada não convertida)",
    "comment": "FUP = escolas fechadas e não convertidas para bolsão. Objetivo: criar argumento específico e fluxo de abordagem para reativar essas escolas. Resultado da reunião deve alimentar t015 (disparo).",
    "owner": "Ana Paula Pimentel",
    "date": "25/fev",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t017",
    "task": "Planejamento março — escalar WhatsApp/Instagram para concorrência e retração",
    "comment": "Definir calendário e segmentação de disparos para março nas frentes de Concorrência e Retração. Incluir: volume estimado, budget, copy base e KPI de acompanhamento. Baseado em aprendizados a009 (copy retração) e a006 (oferta por baldinho).",
    "owner": "Kaka",
    "date": "01/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t018",
    "task": "Reabrir conversas Blip das 27+5 levantadas de caneca",
    "comment": "27 renovação + 5 AA levantaram a mão no caneca (23/02) e não foram contatados. Pimentel reabre conversas na Blip e retoma contato. Apoio: Nath (abordagem SDR) e Vitória (extração da lista — t014). Prioridade: escolas com mais contexto de conversa já iniciada.",
    "owner": "Ana Paula Pimentel",
    "date": "24/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t019",
    "task": "Escalar cenoura para closers — aprovar com Lili",
    "comment": "t008 (cenoura ativação) já concluído. Este é específico para closers. Pimentel propõe o modelo (valor, critério, período) e aprova com Lili antes de comunicar ao time.",
    "owner": "Ana Paula Pimentel",
    "date": "25/fev",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t020",
    "task": "Disparo 4a: fechada > convertida — aguardar oferta Pimentel (bloqueado por t016)",
    "comment": "Disparo de reativação para escolas fechadas não convertidas para bolsão. BLOQUEADO: aguardar Pimentel definir oferta/argumento com time ID (t016). Assim que t016 entregar, Vitória executa o disparo em 4a.",
    "owner": "Vitoria",
    "date": "24/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t021",
    "task": "Avaliar na 4a se vale executar push de reforço nas etapas SDR (último push RR)",
    "comment": "Checkpoint de quarta-feira: Nath avalia RR/SDR do dia e decide com Lili se executa um disparo extra para leads em etapas de SDR. Objetivo: dar último push antes do fechamento de fevereiro. Decisão em 4a → execução no mesmo dia se aprovado.",
    "owner": "Nath Ferreira",
    "date": "25/fev",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  },
  {
    "id": "t022",
    "task": "teste 123",
    "comment": "teste front",
    "owner": "Pedro",
    "date": "25/fev",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": null,
    "completedAt": null
  }
];
