window.WATCHDOG_TODOS = [
  {
    "id": "t179",
    "task": "Nath: calcular custo por aluno cadastrado por frente de campanha. Dados disponíveis no documento de 17/03: LT PART (451 alunos, R$731,16 disparo = R$1,62/aluno), LT Pública (1.827 alunos, R$283,50 disparo = R$0,155/aluno), HT Pública (427 alunos, R$262,44 disparo = R$0,615/aluno). LT Pública é 10x mais eficiente por aluno cadastrado que LT PART — esse dado deve informar alocação de budget restante de março.",
    "comment": "Dados brutos já disponíveis no documento de 17/03. t179 venceu em 16/mar — passou do prazo. Cálculo preliminar: LT PART R$1,62/aluno, LT Pública R$0,155/aluno, HT Pública R$0,615/aluno. LT Pública é disparadamente mais eficiente em custo por aluno cadastrado, mas a frente de maior receita (LT PART) é a mais cara. Esse trade-off precisa ser formalizado.",
    "owner": "Nath Ferreira",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t180",
    "task": "Pimentel: usar Notebook LM para analisar audios de no-show em Renovacao e identificar padroes de cancelamento/ausencia",
    "comment": "Decisao tomada na daily 13/03. Pedro recusou aceitar o argumento de escola ocupada sem analise mais profunda. 16 mimos nao resolveram o comparecimento (insight125). Objetivo: identificar padrao de quando e por que gestoras agendam mas nao aparecem.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t181",
    "task": "Karina e Vitoria: avaliar janela de oportunidade para disparo adicional de Low Touch com ação de vídeo — tarefa absorvida pela decisão de disparo para 2.800 escolas não-convertidas na semana de 23/03; verificar se ainda há escopo residual ou se pode ser concluída",
    "comment": "A daily de 17/03 definiu estratégia completa de disparo de vídeo para LT e HT (particulares e públicas) na semana de 23/03. A t181 foi criada para avaliar janela para disparo adicional — essa janela foi definida na daily. Verificar se há escopo residual ou se a tarefa está absorvida pela decisão tomada.",
    "owner": "Kaka",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t182",
    "task": "Pedro e Karina: enviar briefing do webinar com Antonia Burk para Pimentel (datas, tema, formato)",
    "comment": "Proximo passo explicito da daily 13/03. Webinar confirmado para a primeira semana de abril. Sem briefing na proxima segunda, Pimentel nao pode iniciar planejamento de divulgacao.",
    "owner": "Pedro",
    "date": "16/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t183",
    "task": "Vitoria: confirmar se disparo WA de Retração (base ampliada) foi executado até 18/03 — Retração mensal tem RR/SDR em 71% (amarelo) e Realizadas em 85% (amarelo). Semana atual está verde (150% meta alunos, 132% realizadas), o que pode indicar que disparo anterior surtiu efeito parcial. Validar se a base ampliada está incluída ou se o verde semanal é da base anterior.",
    "comment": "Retração semana verde (289/963 alunos, 150%; Realizadas 4/15, 132%; RR/SDR 0,89/0,76, 117%) contrasta com Retração mensal ainda amarela (RR/SDR 71%, Realizadas 85%). O disparo de base ampliada de t183 pode ser o catalisador para recuperar o mensal — urgente confirmar execução.",
    "owner": "Vitoria",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t184",
    "task": "Lili: dar acesso a Vitoria a planilha sendo fechada com Nath — insumo para analise de custo medio de oferta no CPL",
    "comment": "Proximo passo explicito da daily 13/03. Vitoria precisa da planilha para calcular custo medio de vale-presente e sem trabalho e incorporar ao CPL para comparacao de ROI (insight123).",
    "owner": "Lili",
    "date": "13/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t185",
    "task": "Vitoria: calcular custo medio do vale-presente e do sem trabalho no CPL — apresentar na proxima daily",
    "comment": "Proximo passo da daily 13/03. Depende de t184 (acesso a planilha da Lili). CPL canal + custo medio da oferta por levantada = CPL total. Decisao estrategica: incluir custo da oferta no CPL para comparacao de ROI.",
    "owner": "Vitoria",
    "date": "16/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t186",
    "task": "Karina: confirmar com designers ate 14/03 se pelo menos um aceitou a arte da revista e quando entrega",
    "comment": "Karina confirmou na daily que entraria em contato hoje. Se nenhum designer disponivel, escalar para Pedro imediatamente. Arte da revista e o item com maior lead time do Cerco Magico. Conectada a alerta054.",
    "owner": "Kaka",
    "date": "14/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-13T00:00:00",
    "completedAt": null
  },
  {
    "id": "t188",
    "task": "Checar se houve resposta do disparo de vídeo de ontem em renovação LT (que gerou aumento de 9 para 13 levantadas) e reportar resultado ao grupo",
    "comment": "Tarefa urgente — resultado do disparo de ontem precisa ser monitorado hoje para validar continuidade da estratégia. Prazo inferido: mesmo dia (urgência de acompanhamento de campanha ativa).",
    "owner": "Vitória Riente",
    "date": "17/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t189",
    "task": "Ajustar meta de Marketing considerando receita do ano anterior por escola (não valor fixo de R$109/aluno) e revisar sugestão de texto do vídeo de disparo, levando ao grupo se necessário",
    "comment": "Dois itens agrupados conforme próxima etapa original. Ajuste de meta impacta leitura de performance do Meta Marketing (hoje em 108% com metodologia antiga, 86% após ajuste parcial já citado). Prazo inferido: próximo dia útil (urgência de correção de métrica ativa).",
    "owner": "Vitória Riente",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t190",
    "task": "Verificar as três escolas de concorrência com problema na entrada, incluindo a de 200 alunos e a fechada de 60 alunos de ontem, e reportar status ao grupo",
    "comment": "Meta de alunos em concorrência está em 55% (alerta058). Escolas com problema na entrada distorcem o número. Prazo inferido: próximo dia útil (urgência de correção de dado ativo).",
    "owner": "Nath Ferreira",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t191",
    "task": "Levantar volume de escolas em HT e LT pública e apresentar ao grupo para priorização do disparo de vídeo",
    "comment": "Insumo crítico para definir faseamento e lotes do disparo de 23/03. Sem esse dado o planejamento de lotes fica incompleto. Prazo inferido: próximo dia útil (disparo previsto para semana de 23/03 — planejamento precisa fechar até sexta 20/03).",
    "owner": "Lili",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t192",
    "task": "Fazer dupla checagem na lista das 37 escolas de bolsões para envio de mimos, garantindo que nenhuma já recebeu mimo anteriormente, e alinhar com o comercial após estruturação do envio",
    "comment": "Envio de mimos adiado para amanhã (18/03). Double check é pré-requisito para o envio. Prazo inferido: 18/03 conforme decisão da daily.",
    "owner": "Kaka",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t193",
    "task": "Confirmar ID da jornada de disparo e aprovar texto do vídeo até 20/03 para garantir que primeiro lote saia na segunda-feira 23/03 sem impedimentos",
    "comment": "Vit está aguardando o ID da jornada para definir logística do disparo (Detalhes). Sem o ID o disparo não pode ser configurado. Prazo inferido: sexta 20/03 — última janela útil antes do início dos lotes na semana de 23/03. Alerta062 documenta o risco de atraso.",
    "owner": "Vitória Riente",
    "date": "20/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t194",
    "task": "Formalizar escopo de atuação de Rânia em negócios perdidos: quais bases (anteriores e novas), critério de priorização por receita, script e meta semanal de contatos",
    "comment": "Decisão tomada na daily sem próxima etapa correspondente (Passo 2 — decisão sem ação). Prazo inferido: 2 dias úteis (decisão urgente de alocação de pessoa).",
    "owner": "Ana Paula Pimentel",
    "date": "19/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t195",
    "task": "Informar previsão de retorno do colaborador ausente de renovação pública e avaliar redistribuição temporária de carteira HT Pública",
    "comment": "Ausência de colaborador em HT Pública é fator agravante do zero de reuniões realizadas (alerta064). Com disparo de vídeo para HT Pública planejado para semana de 23/03, o time precisa estar completo ou ter carteira redistribuída para não desperdiçar as levantadas geradas. Prazo inferido: próximo dia útil.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t1",
    "tierLabel": "A fazer",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  },
  {
    "id": "t196",
    "task": "Liberar envio de mimos para as 10 escolas de HT Pública que deram no-show (aprovação confirmada na daily) e executar o envio",
    "comment": "Daily registra decisão explícita: 'ficou decidido que o envio de mimo pode ser liberado amanhã, pois o volume é baixo e o orçamento de mimo está menos utilizado.' Sem tarefa correspondente nas Próximas etapas — decisão sem ação. Prazo: amanhã conforme decisão da daily.",
    "owner": "Ana Paula Pimentel",
    "date": "18/mar",
    "tier": "t2",
    "tierLabel": "Fazendo",
    "warn": null,
    "done": false,
    "priorityRank": null,
    "updatedAt": "2026-03-17T23:56:00",
    "completedAt": null
  }
];
